CREATE TABLE `spt_pph_orang_pribadi` (
	`id` text PRIMARY KEY NOT NULL,
	`npwp` text NOT NULL,
	`tahun_pajak` integer NOT NULL,
	`pembetulan_ke` integer DEFAULT 0 NOT NULL,
	`status_spt` text DEFAULT 'normal' NOT NULL,
	`status_draft` text DEFAULT 'konsep' NOT NULL,
	`metode_pembukuan` text DEFAULT 'pencatatan' NOT NULL,
	`periode_bulan_mulai` integer DEFAULT 1 NOT NULL,
	`periode_bulan_selesai` integer DEFAULT 12 NOT NULL,
	`a7_status_kewajiban_suami_istri` text,
	`a8_npwp_suami_istri` text,
	`b1a_penghasilan_pekerjaan` integer,
	`b1b1_penghasilan_usaha` integer,
	`b1b2_oppt` text,
	`b1b3_norma` text,
	`b1c_penghasilan_dalam_negeri_lainnya` integer,
	`b1d_penghasilan_luar_negeri` integer,
	`c3_ada_pengurang_penghasilan_neto` integer,
	`c5_ptkp_status` text,
	`c8_ada_pengurang_pph_terutang` integer,
	`d10a_ada_pph_dipotong_pihak_lain` integer,
	`d10b_angsuran_pph_25` integer DEFAULT 0 NOT NULL,
	`d10c_stp_pph_25` integer DEFAULT 0 NOT NULL,
	`d10d_ada_pengembalian_kredit_luar_negeri` integer,
	`d10d_jumlah` integer DEFAULT 0 NOT NULL,
	`e11b_ada_sk_pengangsuran_penundaan` integer,
	`e11b_jumlah` integer DEFAULT 0 NOT NULL,
	`f12a_ganti_spt_sebelumnya` integer,
	`g_metode_pengembalian` text,
	`g_nomor_rekening` text,
	`g_nama_bank` text,
	`g_nama_pemilik_rekening` text,
	`h13a_angsuran_teratur` integer,
	`h13b_perhitungan_tersendiri` integer,
	`h13c_angsuran_oppt` integer,
	`i14b_memiliki_utang` integer,
	`i14c_penghasilan_final` integer,
	`i14d_bukan_objek_pajak` integer,
	`i14e_penyusutan_amortisasi_fiskal` integer,
	`i14f_biaya_entertainment` integer,
	`i14g_dividen_luar_negeri` integer,
	`i14h_kelebihan_pph_final` integer DEFAULT 0 NOT NULL,
	`ja_laporan_keuangan` integer,
	`jb_bukti_zakat` integer,
	`jc_bukti_potong_luar_negeri` integer,
	`jd_surat_kuasa_khusus` integer,
	`je_dokumen_lainnya` integer,
	`penandatangan` text DEFAULT 'wajib_pajak' NOT NULL,
	`pph_kurang_lebih_bayar` integer DEFAULT 0 NOT NULL,
	`tanggal_posting` integer,
	`tanggal_dilaporkan` integer,
	`created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`updated_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	FOREIGN KEY (`npwp`) REFERENCES `wajib_pajak`(`npwp`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE UNIQUE INDEX `spt_pph_orang_pribadi_period_unique` ON `spt_pph_orang_pribadi` (`npwp`,`tahun_pajak`,`pembetulan_ke`);--> statement-breakpoint
CREATE TABLE `spt_pph_orang_pribadi_sumber_penghasilan` (
	`id` text PRIMARY KEY NOT NULL,
	`spt_pph_orang_pribadi_id` text NOT NULL,
	`kode` text NOT NULL,
	FOREIGN KEY (`spt_pph_orang_pribadi_id`) REFERENCES `spt_pph_orang_pribadi`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX `spt_pph_orang_pribadi_sumber_penghasilan_unique` ON `spt_pph_orang_pribadi_sumber_penghasilan` (`spt_pph_orang_pribadi_id`,`kode`);