CREATE TABLE `bukti_potong_bp26` (
	`id` text PRIMARY KEY NOT NULL,
	`npwp_pemotong` text NOT NULL,
	`masa_pajak` integer NOT NULL,
	`tahun` integer NOT NULL,
	`status` text DEFAULT 'NORMAL' NOT NULL,
	`nomor_identitas_wp` text DEFAULT '' NOT NULL,
	`nama` text DEFAULT '' NOT NULL,
	`alamat` text DEFAULT '' NOT NULL,
	`negara_asal_id` text,
	`tanggal_lahir` text,
	`tempat_lahir` text DEFAULT '' NOT NULL,
	`nomor_paspor` text DEFAULT '' NOT NULL,
	`nomor_kitas_kitap` text DEFAULT '' NOT NULL,
	`kode_objek_pajak_id` text,
	`fasilitas_pajak_id` text,
	`penghasilan_bruto` real DEFAULT 0 NOT NULL,
	`dpp` real DEFAULT 0 NOT NULL,
	`tarif` real DEFAULT 0 NOT NULL,
	`pajak_penghasilan` real DEFAULT 0 NOT NULL,
	`jenis_dokumen_id` text,
	`nomor_dokumen` text DEFAULT '' NOT NULL,
	`tanggal_dokumen` text,
	`nomor_pemotongan` text,
	`diterbitkan` integer DEFAULT false NOT NULL,
	FOREIGN KEY (`npwp_pemotong`) REFERENCES `wajib_pajak`(`npwp`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`negara_asal_id`) REFERENCES `negara_spt_pph_badan`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`kode_objek_pajak_id`) REFERENCES `kode_objek_pajak_pph`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`fasilitas_pajak_id`) REFERENCES `fasilitas_pajak_ebupot`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`jenis_dokumen_id`) REFERENCES `jenis_dokumen_ebupot`(`id`) ON UPDATE no action ON DELETE no action
);
