CREATE TABLE `bukti_potong_bpa1` (
	`id` text PRIMARY KEY NOT NULL,
	`npwp_pemotong` text NOT NULL,
	`masa_pajak_awal` integer NOT NULL,
	`tahun_awal` integer NOT NULL,
	`masa_pajak_akhir` integer NOT NULL,
	`tahun_akhir` integer NOT NULL,
	`status` text DEFAULT 'NORMAL' NOT NULL,
	`bekerja_di_lebih_dari_satu_pemberi_kerja` integer DEFAULT false NOT NULL,
	`pegawai_asing` integer DEFAULT false NOT NULL,
	`nomor_identitas_wp` text DEFAULT '' NOT NULL,
	`nama` text DEFAULT '' NOT NULL,
	`status_ptkp` text,
	`jabatan` text DEFAULT '' NOT NULL,
	`kode_objek_pajak_id` text,
	`fasilitas_pajak_id` text,
	`jenis_pemotongan` text,
	`gaji_pensiun_tht_jht` real DEFAULT 0 NOT NULL,
	`tunjangan_pph` real DEFAULT 0 NOT NULL,
	`tunjangan_lainnya` real DEFAULT 0 NOT NULL,
	`honorarium` real DEFAULT 0 NOT NULL,
	`premi_asuransi` real DEFAULT 0 NOT NULL,
	`natura` real DEFAULT 0 NOT NULL,
	`tantiem_bonus` real DEFAULT 0 NOT NULL,
	`penghasilan_bruto` real DEFAULT 0 NOT NULL,
	`biaya_jabatan` real DEFAULT 0 NOT NULL,
	`iuran_pensiun` real DEFAULT 0 NOT NULL,
	`zakat` real DEFAULT 0 NOT NULL,
	`jumlah_pengurangan` real DEFAULT 0 NOT NULL,
	`penghasilan_neto` real DEFAULT 0 NOT NULL,
	`nomor_bukti_sebelumnya` text DEFAULT '' NOT NULL,
	`penghasilan_neto_sebelumnya` real DEFAULT 0 NOT NULL,
	`penghasilan_neto_setahun_disetahunkan` real DEFAULT 0 NOT NULL,
	`penghasilan_tidak_kena_pajak` real DEFAULT 0 NOT NULL,
	`penghasilan_kena_pajak` real DEFAULT 0 NOT NULL,
	`tarif` real DEFAULT 0 NOT NULL,
	`pph_pasal_21_atas_pkp` real DEFAULT 0 NOT NULL,
	`pph_pasal_21_terutang` real DEFAULT 0 NOT NULL,
	`pph_pasal_21_dipotong_sebelumnya` real DEFAULT 0 NOT NULL,
	`pph_pasal_21_terutang_pada_ini` real DEFAULT 0 NOT NULL,
	`pph_dipotong_ditanggung_pemerintah` real DEFAULT 0 NOT NULL,
	`pph_kurang_lebih_dipotong_desember` real DEFAULT 0 NOT NULL,
	`jenis_dokumen_id` text,
	`nomor_dokumen` text DEFAULT '' NOT NULL,
	`tanggal_dokumen` text,
	`nomor_pemotongan` text,
	`diterbitkan` integer DEFAULT false NOT NULL,
	FOREIGN KEY (`npwp_pemotong`) REFERENCES `wajib_pajak`(`npwp`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`kode_objek_pajak_id`) REFERENCES `kode_objek_pajak_pph`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`fasilitas_pajak_id`) REFERENCES `fasilitas_pajak_ebupot`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`jenis_dokumen_id`) REFERENCES `jenis_dokumen_ebupot`(`id`) ON UPDATE no action ON DELETE no action
);
