CREATE TABLE `bukti_potong_bpa2` (
	`id` text PRIMARY KEY NOT NULL,
	`npwp_pemotong` text NOT NULL,
	`masa_pajak_awal` integer NOT NULL,
	`tahun_awal` integer NOT NULL,
	`masa_pajak_akhir` integer NOT NULL,
	`tahun_akhir` integer NOT NULL,
	`status` text DEFAULT 'NORMAL' NOT NULL,
	`bekerja_di_lebih_dari_satu_pemberi_kerja` integer DEFAULT false NOT NULL,
	`nomor_identitas_wp` text DEFAULT '' NOT NULL,
	`nama` text DEFAULT '' NOT NULL,
	`nip` text DEFAULT '' NOT NULL,
	`pangkat_golongan` text DEFAULT '' NOT NULL,
	`status_ptkp` text,
	`posisi` text DEFAULT '' NOT NULL,
	`kode_objek_pajak_id` text,
	`jenis_pemotongan` text,
	`gaji_pokok_pensiun` real DEFAULT 0 NOT NULL,
	`tunjangan_istri` real DEFAULT 0 NOT NULL,
	`tunjangan_anak` real DEFAULT 0 NOT NULL,
	`tunjangan_perbaikan_penghasilan` real DEFAULT 0 NOT NULL,
	`tunjangan_struktural_fungsional` real DEFAULT 0 NOT NULL,
	`tunjangan_beras` real DEFAULT 0 NOT NULL,
	`tunjangan_lain_lain` real DEFAULT 0 NOT NULL,
	`penghasilan_tetap_teratur_lainnya` real DEFAULT 0 NOT NULL,
	`penghasilan_bruto` real DEFAULT 0 NOT NULL,
	`biaya_jabatan` real DEFAULT 0 NOT NULL,
	`iuran_pensiun` real DEFAULT 0 NOT NULL,
	`zakat` real DEFAULT 0 NOT NULL,
	`jumlah_pengurangan` real DEFAULT 0 NOT NULL,
	`penghasilan_neto` real DEFAULT 0 NOT NULL,
	`nomor_bukti_sebelumnya` text DEFAULT '' NOT NULL,
	`penghasilan_neto_sebelumnya` real DEFAULT 0 NOT NULL,
	`penghasilan_neto_setahun_disetahunkan` real DEFAULT 0 NOT NULL,
	`penghasilan_tidak_kena_pajak` real DEFAULT 0 NOT NULL,
	`penghasilan_kena_pajak` real DEFAULT 0 NOT NULL,
	`tarif` real DEFAULT 0 NOT NULL,
	`pph_pasal_21_atas_pkp` real DEFAULT 0 NOT NULL,
	`pph_pasal_21_terutang` real DEFAULT 0 NOT NULL,
	`pph_pasal_21_dipotong_sebelumnya` real DEFAULT 0 NOT NULL,
	`pph_pasal_21_terutang_pada_ini` real DEFAULT 0 NOT NULL,
	`pph_pasal_21_yang_telah_dipotong` real DEFAULT 0 NOT NULL,
	`pph_kurang_lebih_dipotong_desember` real DEFAULT 0 NOT NULL,
	`nomor_pemotongan` text,
	`diterbitkan` integer DEFAULT false NOT NULL,
	FOREIGN KEY (`npwp_pemotong`) REFERENCES `wajib_pajak`(`npwp`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`kode_objek_pajak_id`) REFERENCES `kode_objek_pajak_pph`(`id`) ON UPDATE no action ON DELETE no action
);
