// Bagian I and II live on their own child tables (spt_ppn_penyerahan /
// spt_ppn_perolehan), so a fresh spt_ppn row needs a matching all-zero row in
// each of them. Everything else here is inserted straight onto spt_ppn.
export function createEmptySptPpnFields({ nama = '' }: { nama?: string } = {}) {
	return {
		penyerahan: {
			iA1: 0,
			iA2HargaJual: 0,
			iA2DppNilaiLain: 0,
			iA2Ppn: 0,
			iA2Ppnbm: 0,
			iA3HargaJual: 0,
			iA3DppNilaiLain: 0,
			iA3Ppn: 0,
			iA3Ppnbm: 0,
			iA4HargaJual: 0,
			iA4Ppn: 0,
			iA4Ppnbm: 0,
			iA5HargaJual: 0,
			iA5DppNilaiLain: 0,
			iA5Ppn: 0,
			iA5Ppnbm: 0,
			iA6HargaJual: 0,
			iA6DppNilaiLain: 0,
			iA6Ppn: 0,
			iA6Ppnbm: 0,
			iA7HargaJual: 0,
			iA7DppNilaiLain: 0,
			iA7Ppn: 0,
			iA7Ppnbm: 0,
			iA8HargaJual: 0,
			iA8DppNilaiLain: 0,
			iA8Ppn: 0,
			iA8Ppnbm: 0,
			iA9HargaJual: 0,
			iA9DppNilaiLain: 0,
			iA9Ppn: 0,
			iA9Ppnbm: 0,
			iAJumlahHargaJual: 0,
			iAJumlahPpn: 0,
			iAJumlahPpnbm: 0,
			iB: 0,
			iC: 0
		},

		perolehan: {
			iiADpp: 0,
			iiAPpn: 0,
			iiAPpnbm: 0,
			iiBDpp: 0,
			iiBDppNilaiLain: 0,
			iiBPpn: 0,
			iiBPpnbm: 0,
			iiCDpp: 0,
			iiCPpn: 0,
			iiCPpnbm: 0,
			iiDDpp: 0,
			iiDDppNilaiLain: 0,
			iiDPpn: 0,
			iiDPpnbm: 0,
			iiE: 0,
			iiF: 0,
			iiGDpp: 0,
			iiGPpn: 0,
			iiHDpp: 0,
			iiHDppNilaiLain: 0,
			iiHPpn: 0,
			iiHPpnbm: 0,
			iiI: 0,
			iiJ: 0
		},

		iiiA: 0,
		iiiB: 0,
		iiiC: 0,
		iiiD: 0,
		iiiE: 0,
		iiiF: 0,
		iiiG: 0,
		iiiHGantiSptSebelumnya: false,
		iiiHTindakan: null,
		iiiHLampiranNamaFile: null,
		iiiHRekeningPilihBank: null,
		iiiHRekeningNomor: null,
		iiiHRekeningNamaBank: null,
		iiiHRekeningNamaPemilik: null,

		ivDpp: 0,
		ivPpn: 0,

		v: 0,

		viA: 0,
		viB: 0,
		viC: 0,
		viD: 0,
		viE: 0,
		viF: false,

		viiADpp: 0,
		viiADppNilaiLain: 0,
		viiAPpn: 0,
		viiAPpnbm: 0,
		viiBDpp: 0,
		viiBDppNilaiLain: 0,
		viiBPpn: 0,
		viiBPpnbm: 0,
		viiCDpp: 0,
		viiCDppNilaiLain: 0,
		viiCPpn: 0,
		viiCPpnbm: 0,

		viiiADpp: 0,
		viiiADppNilaiLain: 0,
		viiiAPpn: 0,
		viiiAPpnbm: 0,
		viiiBDpp: 0,
		viiiBDppNilaiLain: 0,
		viiiBPpn: 0,
		viiiBPpnbm: 0,
		viiiCDpp: 0,
		viiiCDppNilaiLain: 0,
		viiiCPpn: 0,
		viiiCPpnbm: 0,
		viiiD: false,

		ixA: true,
		ixB: true,

		xSetuju: false,
		xDitandatanganiOleh: null,
		xKotaPenandatanganSpt: 'Jakarta',
		xNama: nama,
		xJabatan: 'Direktur',
		xBatasWaktuPenyampaian: new Date().toISOString().slice(0, 10)
	};
}
