import { notInArray } from 'drizzle-orm';
import { referensi_lampiran_spt_pph_orang_pribadi } from '../../schema';
import type { SeedContext } from '../context';
import { batchInsert } from '../helpers';

export const name = '016 SPT PPh Orang Pribadi lampiran reference lists';

// Transcribed from the live Coretax dropdowns, captured in
// docs/ui-reference/coretax/spt-1770-lampiran/REFERENCE-LISTS.txt.
//
// Only descriptions are stored: our KODE fields are plain text the peserta
// types, so the lists do not need code/description pairs. Order is DJP's own and
// is preserved verbatim, including the duplicates and non-country entries in the
// negara list (Angola and Jersey each appear twice). Do not sort or dedupe.
//
// These are the 17 lists that L-1 and L-2 need. The remaining 3 (L-3A-4 B and
// L-5 B/C) are in the same source file and can be added the same way.
const daftar: Record<string, readonly string[]> = {
	l1_a1_deskripsi: [
		'Uang Tunai/Bank Note/Koin',
		'Tabungan (Bank/Lembaga Keuangan)',
		'Giro',
		'Deposito',
		'Uang elektronik',
		'Cek',
		'Wessel',
		'Commercial Paper',
		'Setara Kas Lainnya'
	],
	negara: [
		'Aruba',
		'Afganistan',
		'Angola',
		'Angola',
		'Kepulauan Aland',
		'Albania',
		'Andorra',
		'Uni Emirat Arab',
		'Argentina',
		'Armenia',
		'Samoa Amerika',
		'Antartika',
		'Wilayah Selatan Prancis',
		'Antigua dan Barbuda',
		'Australia',
		'Austria',
		'Azerbaijan',
		'Burundi',
		'Belgia',
		'Benin',
		'Bonaire, Sint Eustatius dan Saba',
		'Burkina Faso',
		'Bangladesh',
		'Bulgaria',
		'Bahrain',
		'Bahama',
		'Bosnia dan Herzegovina',
		'Santo Barthelemy',
		'Belarusia',
		'Belize',
		'Bermuda',
		'Negara Majemuk Bolivia',
		'Brasil',
		'Barbados',
		'Brunei Darussalam',
		'Bhutan',
		'Pulau Bouvet',
		'Botswana',
		'Republik Afrika Tengah',
		'Kanada',
		'Kepulauan Cocos (Keeling)',
		'Swiss',
		'Cile',
		'Tiongkok',
		'Pantai Gading',
		'Kamerun',
		'Republik Demokratik Kongo',
		'Kongo',
		'Kepulauan Cook',
		'Kolombia',
		'Komoro',
		'Cabo Verde',
		'Kosta Rika',
		'Kuba',
		'Curacao',
		'Pulau Natal',
		'Kepulauan Cayman',
		'Siprus',
		'Republik Ceko',
		'Jerman',
		'Djibouti',
		'Dominika',
		'Denmark',
		'Republik Dominika',
		'Aljazair',
		'Ekuador',
		'Mesir',
		'Eritrea',
		'Sahara Barat',
		'Spanyol',
		'Estonia',
		'Etiopia',
		'Finlandia',
		'Fiji',
		'Kepulauan Falkland (Malvinas)',
		'Prancis',
		'Kepulauan Faroe',
		'Negara Federasi Mikronesia',
		'Gabon',
		'Britania Raya',
		'Georgia',
		'Guernsey',
		'Ghana',
		'Gibraltar',
		'Guinea',
		'Guadeloupe',
		'Gambia',
		'Guinea-Bissau',
		'Ekuator Guinea',
		'Yunani',
		'Granada',
		'Greenland',
		'Georgia Selatan dan Kepulauan Sandwich Selatan',
		'Guatemala',
		'Guyana Prancis',
		'Guam',
		'Guyana',
		'Hongkong',
		'Pulau Heard dan Kepulauan McDonald',
		'Honduras',
		'Kroasia',
		'Haiti',
		'Hongaria',
		'Indonesia',
		'Pulau Man',
		'India',
		'Wilayah Samudra Hindia Britania',
		'Irlandia',
		'Republik Islam Iran',
		'Irak',
		'Islandia',
		'Israel',
		'Italia',
		'Jamaika',
		'Jersey',
		'Jersey',
		'Yordania',
		'Jepang',
		'Kazakstan',
		'Kenya',
		'Kirgistan',
		'Kamboja',
		'Kiribati',
		'Saint Kitts dan Nevis',
		'Korea (Republik)',
		'Kosovo',
		'KOREA (STH), REPUBLIC',
		'KOREA (NTH) - DEMOCRATIC PEOPLES',
		'Kuwait',
		'Republik Demokratik Rakyat Laos',
		'Libanon',
		'Liberia',
		'Libya',
		'Santa Lucia',
		'Liechtenstein',
		'Tanpa kewarganegaraan',
		'Sri Lanka',
		'Lesoto',
		'Lithuania',
		'Luksemburg',
		'Latvia',
		'Makao',
		'Santo Martin (bagian Prancis)',
		'Maroko',
		'Monako',
		'Republik Moldova',
		'Madagaskar',
		'Maladewa',
		'Meksiko',
		'Kepulauan Marshall',
		'Republik Makedonia Bekas Yugoslavia',
		'Mali',
		'Malta',
		'Myanmar',
		'Montenegro',
		'Mongolia',
		'Kepulauan Mariana Utara',
		'Mozambik',
		'Mauritania',
		'Montserrat',
		'Martinik',
		'Mauritius',
		'Malawi',
		'Malaysia',
		'Namibia',
		'Kaledonia Baru',
		'Niger',
		'Pulau Norfolk',
		'Nigeria',
		'Nikaragua',
		'Niue',
		'Belanda',
		'Belanda - Kerajaan',
		'Norwegia',
		'Nepal',
		'Nauru',
		'Selandia Baru',
		'Oman',
		'Pakistan',
		'Panama',
		'UNITED NATIONS AGENCY',
		'Pitcairn',
		'Peru',
		'Filipina',
		'Palau',
		'Papua Nugini',
		'Polandia',
		'Perancis',
		'Puerto Riko',
		'Republik Rakyat Demokratik Korea',
		'Portugal',
		'Paraguay',
		'Negara Palestina',
		'PALESTINE',
		'Polinesia',
		'Qatar',
		'Reuni',
		'Pengungsi (Konvensi Pasal 1, 1951)',
		'Republik Irlandia',
		'Rumania (New Code)',
		'Rumania',
		'Federasi Rusia',
		'Rwanda',
		'Arab Saudi',
		'Pulau Solomon',
		'Sudan',
		'Senegal',
		'Singapura',
		'Saint Helena, Ascension dan Tristan da Cunha',
		'Svalbard dan Jan Mayen',
		'Sierra Leone',
		'El Salvador',
		'San Marino',
		'Somalia',
		'Saint Pierre dan Miquelon',
		'Serbia',
		'Sudan Selatan',
		'Sao Tome dan Principe',
		'Suriname',
		'Slowakia',
		'Slovenia',
		'SLOVAK REPUBLIC',
		'SWAZILAND',
		'Swedia',
		'Eswatini',
		'Sint Maarten (bagian Belanda)',
		'Seychelles',
		'Republik Arab Suriah',
		'Kepulauan Turks dan Caicos',
		'Chad',
		'Togo',
		'Thailand',
		'Tajikistan',
		'Tokelau',
		'Turkmenistan',
		'Timor Leste',
		'TIMOR LESTE DEMOCRATIC REPUBLIC',
		'Tonga',
		'Trinidad dan Tobago',
		'Tunisia',
		'Turki',
		'Tuvalu',
		'TAIWAN - PROVINCE OF CHINA',
		'Taiwan',
		'Tanzania, Republik Bersatu',
		'Uganda',
		'Ukraina',
		'Kepulauan Terpencil Kecil Amerika Serikat',
		'Uruguay',
		'Amerika Serikat',
		'Uzbekistan',
		'Tahta Suci (Negara Kota Vatikan)',
		'Saint Vincent dan Grenadines',
		'Venezuela (Republik Bolivarian)',
		'Kepulauan Virgin (Inggris)',
		'Kepulauan Virgin (Amerika Serikat)',
		'Vietnam',
		'Vanuatu',
		'Wallis dan Futuna',
		'Samoa',
		'Yaman',
		'Mayotte',
		'Afrika Selatan',
		'Zambia',
		'Zimbabwe'
	],
	keterangan_pps: [
		'Harta PPS',
		'Harta Investasi PPS'
	],
	l1_a2_deskripsi: [
		'Piutang Usaha',
		'Piutang Afiliasi',
		'Piutang lainnya'
	],
	l1_a3_deskripsi: [
		'Saham yang dibeli untuk dijual kembali',
		'Saham non bursa',
		'Saham bursa',
		'Obligasi perusahaan',
		'Obligasi pemerintah Indonesia (Obligasi Ritel Indonesia, Surat Berharga Syariah Negara, dll)',
		'Surat Utang lainnya',
		'Kontrak Investasi Kolektif (KIK) termasuk Reksadana, dan investasi yang dikonversikan ke unit..',
		'Instrumen derivatif (right, warran, kontrak berjangka, opsi, dll)',
		'Penyertaan modal dalam perusahaan lain yang bukan atas saham meliputi penyertaan modal pada C..',
		'Asuransi',
		'Unit Link di Asuransi',
		'Investasi lainnya (termasuk Cryptocurrency, Trust Fund dan Investasi lainnya)'
	],
	l1_a4_tipe: [
		'Sepeda',
		'Sepeda Motor',
		'Mobil Penumpang',
		'Bis',
		'Kendaraan Angkutan Jalan',
		'Kendaraan Tujuan Khusus',
		'Kereta',
		'Pesawat Terbang',
		'Kapal',
		'Mesin',
		'Gerobak',
		'Kapal Pesiar',
		'Harta bergerak lainnya'
	],
	l1_a4_kepemilikan: [
		'Atas nama pihak lain',
		'Atas nama sendiri'
	],
	l1_a5_deskripsi: [
		'Tanah Kosong',
		'Tanah dan/atau Bangunan untuk Tempat Tinggal',
		'Apartemen',
		'Kapal',
		'Tanah atau Lahan untuk Usaha (seperti lahan pertanian, perkebunan, perikanan darat, dan sejen..',
		'Tanah dan/atau Bangunan untuk Usaha (toko, pabrik, gudang, dan sejenisnya)',
		'Tanah dan/atau Bangunan yang Disewakan',
		'Harta Tidak Bergerak Lainnya'
	],
	l1_a5_sumber_kepemilikan: [
		'Utang',
		'Hadiah',
		'Hibah',
		'Warisan',
		'Sumber lainnya',
		'Hasil Sendiri'
	],
	l1_a6_deskripsi: [
		'Paten',
		'Royalti',
		'Merek dagang',
		'Harta Tidak Berwujud Lainnya',
		'Emas Batangan',
		'Emas Perhiasan',
		'Batangan Non-Emas',
		'Perhiasan Non-Emas',
		'Permata (intan,berlian,batu mulia lainnya)',
		'Barang-barang seni dan antik (barang-barang seni, barang-barang antik)',
		'Peralatan olahraga khusus',
		'Peralatan elektronik',
		'Perabot Rumah Tangga',
		'Peralatan Kantor',
		'Jet Ski',
		'Persediaan usaha',
		'Harta lainnya'
	],
	l1_b_deskripsi: [
		'Utang Bank / Lembaga Keuangan Bukan Bank (KPR, Leasing Kendaraan Bermotor, dan sejenisnya)',
		'Kartu Kredit',
		'Utang Afiliasi (Pinjaman dari pihak yang memiliki hubungan istimewa sebagaimana dimaksud dala..',
		'Utang Lainnya'
	],
	l1_b_keterangan: [
		'Debt in relation to Voluntary Disclosure Program Assets/Utang terkait PPS'
	],
	l1_e_jenis_pajak: [
		'PPh Pasal 15',
		'PPh Pasal 21',
		'PPh Pasal 22',
		'PPh Pasal 23',
		'PPh Pasal 26',
		'PPh Ditanggung Pemerintah',
		'PPh Ditanggung Pemerintah(Proyek Bantuan Luar Negeri)',
		'Nilai LB dalam SPT yang dianggap bukan merupakan lebih bayar'
	],
	l2_a_jenis_penghasilan: [
		'Upah Pegawai Tidak Tetap yang Dibayarkan secara Bulanan yang Mendapat Fasilitas di Daerah Ter..',
		'Imbalan kepada Bukan Pegawai Lainnya yang mendapat fasilitas di daerah tertentu',
		'Upah Pegawai Tidak Tetap yang Dibayarkan secara Harian, Mingguan, Satuan dan Borongan dengan ..',
		'Upah Pegawai Tidak Tetap yang Dibayarkan secara Harian, Mingguan, Satuan dan Borongan dengan ..',
		'Penghasilan yang Diterima atau Diperoleh Pegawai Tetap yang Menerima Fasilitas di Daerah Tert..',
		'Uang Pesangon yang Dibayarkan Sekaligus',
		'Uang Manfaat Pensiun, Tunjangan Hari Tua atau Jaminan Hari Tua dan Pembayaran Sejenis yang Di..',
		'Honor dan Imbalan Lain yang Dibebankan Dibebankan kepada APBN atau APBD yang Diterima oleh PN..',
		'Honor atau Imbalan Lain yang Dibebankan kepada APBN atau APBD yang Diterima oleh PNS Golongan..',
		'Honor atau Imbalan Lain yang Dibebankan kepada APBN atau APBD yang Diterima oleh Pejabat Nega.',
		'Honor atau Imbalan Lain yang Dibebankan kepada APBN atau APBD yang Diterima oleh PNS Golongan.',
		'Objek PPh Pasal 21 yang Bersifat Final Lainnya',
		'Penghasilan Sehubungan dengan Transaksi Penjualan Barang, Penyerahan Jasa, dan/atau Persewaan.',
		'Penghasilan yang Diterima atau Diperoleh Pedagang Dalam Negeri Penjualan Barang, Penyerahan J.',
		'Penjualan BBM oleh Pertamina atau Anak Perusahaan Pertamina Kepada SPBU (Final)',
		'Penjualan BBM oleh Badan Usaha Selain Pertamina atau Anak Perusahaan Pertamina Kepada SPBU/Ag.',
		'Penjualan BBG oleh produsen/importir Kepada SPBU/Agen/Penyalur (Final)',
		'Penjualan BBM oleh Pertamina atau Anak Perusahaan Pertamina kepada Agen/Penyalur selain SPBU .',
		'Penghasilan Sehubungan dengan Aset Kripto yang dipungut oleh Penyelenggara Perdagangan Melalu.',
		'Penghasilan Sehubungan dengan Aset Kripto yang dipungut oleh Penyelenggara Perdagangan Melalu.',
		'Penghasilan Sehubungan dengan Aset Kripto (Setor Sendiri)',
		'Penghasilan Sehubungan dengan Aset Kripto yang dipungut oleh Penyelenggara Perdagangan Melalu.',
		'Penghasilan Sehubungan dengan Aset Kripto yang dipungut oleh Penyelenggara Perdagangan Melalu.',
		'Penghasilan Sehubungan dengan Transaksi Aset Kripto di Penyelenggara Perdagangan Melalui Sist.',
		'Penghasilan Sehubungan dengan Transaksi Aset Kripto di Penyelenggara Perdagangan Melalui Sist.',
		'Bunga Obligasi, Surat Utang Negara, atau Obligasi Daerah yang Diterima Wajib Pajak Dalam Nege.',
		'Bunga Obligasi yang Diterima Wajib Pajak Dalam Negeri dan Bentuk Usaha Tetap yang diadministr.',
		'Diskonto Surat Perbendaharaan Negara yang Diterima Wajib Pajak Dalam Negeri dan Bentuk Usaha .',
		'Diskonto Surat Perbendaharaan Negara yang Diterima Wajib Pajak Penduduk/Berkedudukan di Luar .',
		'Bunga Obligasi yang Diterima Wajib Pajak Dalam Negeri dan Bentuk Usaha Tetap',
		'Pengalihan Hak atas Tanah dan/atau Bangunan',
		'Pengalihan Rumah Sederhana dan Rumah Susun Sederhana yang Dilakukan oleh WP yang Usaha Pokokn.',
		'Pengalihan Hak atas Tanah dan/atau Bangunan kepada Pemerintah, BUMN yang Mendapat Penugasan K.',
		'Persewaan Tanah dan/atau Bangunan',
		'Kekurangan penyetoran PPh final dari pemungutan Pihak Lain (SIPP)-Persewaan Tanah dan/atau Ba.',
		'Bunga Tabungan dan Bunga Deposito yang Ditempatkan di Dalam Negeri yang Dananya Bersumber Sel.',
		'Bunga Deposito yang Ditempatkan di Dalam Negeri (mata uang IDR bersumber dari DHE tenor 1 bul.',
		'Bunga Deposito yang Ditempatkan di Dalam Negeri (mata uang IDR bersumber dari DHE tenor 3 bul.',
		'Bunga Deposito yang Ditempatkan di Dalam Negeri (mata uang IDR bersumber dari DHE tenor 6 bul.',
		'Bunga Deposito yang Ditempatkan di Dalam Negeri (mata uang USD bersumber dari DHE tenor 1 bul.',
		'Bunga Deposito yang Ditempatkan di Dalam Negeri (mata uang USD bersumber dari DHE tenor 3 bul.',
		'Bunga Deposito yang Ditempatkan di Dalam Negeri (mata uang USD bersumber dari DHE tenor 6 bul.',
		'Bunga Deposito yang Ditempatkan di Dalam Negeri (mata uang USD bersumber dari DHE tenor lebih.',
		'Bunga Deposito/Tabungan yang Ditempatkan di Luar Negeri Melalui Bank yang Didirikan atau Bert.',
		'Diskonto Sertifikat Bank Indonesia',
		'Jasa Giro',
		'Hadiah Undian',
		'Transaksi Penjualan Saham di Bursa Efek (Bukan Saham Pendiri)',
		'Transaksi Penjualan Saham di Bursa Efek (Saham Pendiri)',
		'Transaksi Penjualan Saham Milik Perusahaan Modal Ventura Tidak di Bursa Efek',
		'Jasa Konstruksi Berupa Jasa Perencanaan Konstruksi (Dengan Kualifikasi Usaha) yang Disetor Se.',
		'Jasa Konstruksi Berupa Jasa Perencanaan Konstruksi (Tanpa Kualifikasi Usaha)',
		'Jasa Konstruksi Berupa Jasa Pelaksanaan Konstruksi (Kualifikasi Usaha Kecil)',
		'Jasa Konstruksi Berupa Jasa Pelaksanaan Konstruksi (Kualifikasi Usaha Menengah dan Besar)',
		'Jasa Konstruksi Berupa Jasa Pelaksanaan Konstruksi (Tanpa Kualifikasi Usaha)',
		'Jasa Konstruksi Berupa Jasa Pengawasan Konstruksi (Dengan Kualifikasi Usaha)',
		'Jasa Konstruksi Berupa Jasa Pengawasan Konstruksi (Tanpa Kualifikasi Usaha)',
		'Pekerjaan Konstruksi yang Dilakukan oleh Penyedia Jasa yang Memiliki Sertifikat Badan Usaha K.',
		'Pekerjaan Konstruksi yang Dilakukan oleh Penyedia Jasa yang Tidak Memiliki Sertifikat Badan U.',
		'Pekerjaan Konstruksi yang Dilakukan oleh Penyedia Jasa yang Memiliki Sertifikat Selain Sertif.',
		'Pekerjaan Konstruksi Terintegrasi yang Dilakukan oleh Penyedia Jasa yang Memiliki Sertifikat .',
		'Pekerjaan Konstruksi Terintegrasi yang Dilakukan oleh Penyedia Jasa yang Tidak Memiliki Serti.',
		'Jasa Konsultansi Konstruksi yang Dilakukan oleh Penyedia Jasa yang Memiliki Sertifikat Badan .',
		'Jasa Konsultansi Konstruksi yang Dilakukan oleh Penyedia Jasa yang Tidak Memiliki Sertifikat .',
		'Kekurangan penyetoran PPh final dari pemungutan Pihak Lain (SIPP)-Pekerjaan Konstruksi yang D.',
		'Kekurangan penyetoran PPh final dari pemungutan Pihak Lain (SIPP)-Pekerjaan Konstruksi yang D.',
		'Kekurangan penyetoran PPh final dari pemungutan Pihak Lain (SIPP)-Pekerjaan Konstruksi yang D.',
		'Kekurangan penyetoran PPh final dari pemungutan Pihak Lain (SIPP)-Pekerjaan Konstruksi Terint.',
		'Kekurangan penyetoran PPh final dari pemungutan Pihak Lain (SIPP)-Pekerjaan Konstruksi Terint.',
		'Kekurangan penyetoran PPh final dari pemungutan Pihak Lain (SIPP)-Jasa Konsultansi Konstruksi.',
		'Kekurangan penyetoran PPh final dari pemungutan Pihak Lain (SIPP)-Jasa Konsultansi Konstruksi.',
		'Kekurangan penyetoran PPh final dari pemungutan Pihak Lain (SIPP)-Jasa Konstruksi Berupa Jasa.',
		'Kekurangan penyetoran PPh final dari pemungutan Pihak Lain (SIPP)-Jasa Konstruksi Berupa Jasa.',
		'Kekurangan penyetoran PPh final dari pemungutan Pihak Lain (SIPP)-Jasa Konstruksi Berupa Jasa.',
		'Kekurangan penyetoran PPh final dari pemungutan Pihak Lain (SIPP)-Jasa Konstruksi Berupa Jasa.',
		'Kekurangan penyetoran PPh final dari pemungutan Pihak Lain (SIPP)-Jasa Konstruksi Berupa Jasa.',
		'Kekurangan penyetoran PPh final dari pemungutan Pihak Lain (SIPP)-Jasa Konstruksi Berupa Jasa.',
		'Kekurangan penyetoran PPh final dari pemungutan Pihak Lain (SIPP)-Jasa Konstruksi Berupa Jasa.',
		'Imbalan yang Diterima/Diperoleh Sehubungan dengan Pengangkutan Orang dan/atau Barang Termasuk.',
		'Imbalan yang Dibayarkan/Terutang kepada Perusahaan Pelayaran Dalam Negeri',
		'Kekurangan penyetoran PPh final dari pemungutan Pihak Lain (SIPP)-Imbalan yang Dibayarkan/Ter.',
		'Kekurangan penyetoran PPh final dari pemungutan Pihak Lain (SIPP)-Imbalan yang Diterima/Diper.',
		'Imbalan yang Dibayarkan/Terutang kepada Perusahaan Pelayaran dan/atau Penerbangan Luar Negeri.',
		'Imbalan Charter Kapal Laut dan/atau Pesawat Udara yang Dibayarkan/ Terutang kepada Perusahaan.',
		'Kekurangan penyetoran PPh final dari pemungutan Pihak Lain (SIPP)-Imbalan Charter Kapal Laut .',
		'Penghasilan Wajib Pajak Luar Negeri yang Mempunyai Kantor Perwakilan Dagang di Indonesia',
		'Revaluasi atau penilaian kembali aset tetap',
		'Bunga Simpanan yang Dibayarkan oleh Koperasi kepada Anggota Wajib Pajak Orang Pribadi (bunga .',
		'Bunga Simpanan yang Dibayarkan oleh Koperasi kepada Anggota Wajib Pajak Orang Pribadi (bunga .',
		'Dividen yang Diterima/Diperoleh Wajib Pajak Orang Pribadi Dalam Negeri',
		'Uplift Hulu Migas',
		'Participating Interest Eksplorasi Hulu Migas',
		'Participating Interest Eksploitasi Hulu Migas',
		'Pemotongan atau pemungutan PPh atas penjualan barang atau penyerahan jasa yang dilakukan oleh.',
		'Pemotongan atau pemungutan PPh atas transaksi pembelian yang dilakukan oleh Wajib Pajak denga.',
		'Pemotongan atau Pemungutan PPh atas transaksi penjualan barang atau penyerahan jasa yang dila.',
		'Pemotongan atau Pemungutan PPh atas transaksi penjualan barang atau penyerahan jasa yang dila.',
		'Pemotongan atau pemungutan PPh atas transaksi pembelian yang dilakukan oleh Wajib Pajak yang .',
		'Penghasilan yang dikenakan pajak bersifat final sesuai Peraturan Pemerintah Nomor 23/55 (Dise.',
		'Perjanjian Pengikatan Jual Beli',
		'Penghasilan Wajib Pajak yang Melakukan Kegiatan Usaha Jasa Maklon (Contract Manufacturing) In',
		'Penghasilan yang Diterima atau Diperoleh Sehubungan dengan Kerja Sama dengan Lembaga Pengelol',
		'Penghasilan istri dari satu pemberi kerja',
		'Penghasilan Final Lainnya'
	],
	l2_b_jenis_penghasilan: [
		'Dividen atau bagian laba',
		'Pembebasan utang',
		'Hibah',
		'Bantuan/Sumbangan',
		'Warisan',
		'Penerimaan Zakat dan Sumbangan Keagamaan yang sifatnya wajib',
		'Bagian Laba Anggota Perseroan Komanditer Tidak Atas Saham, Persekutuan, Perkumpulan, Firma, K..',
		'Klaim asuransi kesehatan, kecelakaan, jiwa, dwiguna, beasiswa',
		'Beasiswa',
		'Hadiah langsung yang diberikan kepada semua pembeli/konsumen akhir tanpa diundi',
		'Objek PPh tertentu bagi TKA yang memiliki keahlian tertentu (expatriate regime)',
		'Natura dan kenikmatan yang dikecualikan dari objek pajak',
		'SHU dari koperasi',
		'Penghasilan lain yang tidak termasuk objek pajak'
	],
	l2_c_jenis_penghasilan: [
		'Penghasilan dari Pekerjaan Bebas',
		'Penghasilan dari kegiatan usaha',
		'Pendapatan lain dari kegiatan usaha atau pekerjaan bebas',
		'Gaji, tunjangan, honorarium, bonus, jasa produksi',
		'Upah honorarium yg diterima oleh pegawai tidak tetap',
		'Uang pesangon diterima sekaligus',
		'Manfaat Pensiun, Tunjangan Hari Tua, atau Jaminan Hari Tua dibayarkan sekaligus',
		'Uang pensiun yang diterima secara berkala/bulanan oleh penerima pensiun',
		'Penghasilan lain yang berhubungan dengan pekerjaan',
		'Sewa tanah dan atau bangunan',
		'Sewa harta selain tanah dan atau bangunan',
		'Dividen',
		'Bunga',
		'Obligasi',
		'Royalti',
		'Keuntungan Penjualan Harta',
		'Bunga Deposito',
		'Bunga Tabungan',
		'Surat Berharga/Sekuritas',
		'Penjualan Saham di Bursa',
		'Pengalihan atau Penjualan Tanah Bangunan',
		'Keuntungan Selisih Mata Uang Asing',
		'Penghasilan lain-lain dari Modal atau Aset/Harta',
		'Pembebasan Utang',
		'Hibah',
		'Bantuan/Sumbangan',
		'Warisan',
		'Hadiah/Undian',
		'Penghasilan lain'
	],
	mata_uang: [
		'UAE Dirham: UNITED ARAB EMIRATES',
		'Afghani Afghanistan',
		'Albania Lek',
		'Gulden Antillen Belanda',
		'Peso Argentina',
		'Dolar Australia',
		'Gulden Aruba',
		'Manat Azerbaijan',
		'Mark Konvertibel Bosnia dan Herzegovina',
		'Dolar Barbados',
		'Bangladeshi Taka',
		'Lev Bulgaria',
		'Dolar Bermuda',
		'Dolar Brunei Darussalam',
		'Boliviano Bolivia',
		'Real Brazil',
		'Dolar Bahama',
		'Pula Botswana',
		'Rubel Belarusia',
		'Dolar Belize',
		'Dolar Kanada',
		'Franc Swiss',
		'Peso Chili',
		'Yuan Renminbi: CHINA',
		'Peso Kolombia',
		'Kolon Kosta Rika',
		'Peso Kuba',
		'Koruna Republik Ceko',
		'Krone Denmark',
		'Peso Republik Dominika',
		'Pound Mesir',
		'Negara Anggota Euro',
		'Dolar Fiji',
		'Kepulauan Falkland (Malvinas) Pound',
		'Pound Inggris',
		'Pound Guernsey',
		'Cedi Ghana',
		'Pound Gibraltar',
		'Quetzal Guatemala',
		'Dolar Guyana',
		'Dollar Hongkong',
		'Lempira Honduras',
		'Kuna Kroasia',
		'Forint Hongaria',
		'Rupiah Indonesia',
		'Shekel Israel',
		'Pulau Man Pound',
		'Rupee India',
		'Rial Iran',
		'Krona Islandia',
		'Jersey Pound',
		'Dolar Jamaika',
		'Yen Jepang',
		'Som Kirgistan',
		'Kamboja Riel',
		'Won Korea Utara',
		'Won Korea Selatan',
		'Dolar Kepulauan Cayman',
		'Tenge Kazakstan',
		'Kip Laos',
		'Pound Lebanon',
		'Rupee Sri Lanka',
		'Dolar Liberia',
		'Denar Makedonia',
		'Tughrik Mongolia',
		'Rupee Mauritius',
		'Peso Meksiko',
		'Ringgit Malaysia',
		'Metical Mozambik',
		'Dolar Namibia',
		'Naira Nigeria',
		'Cordoba Nikaragua',
		'Krone Norwegia',
		'Rupee Nepal',
		'Dolar Selandia Baru',
		'Rial Oman',
		'Balboa Panama',
		'Sol Peru',
		'Peso Filipina',
		'Rupee Pakistan',
		'Zloty Polandia',
		'Guarani Paraguay',
		'Riyal Qatar',
		'Leu Romania',
		'Dinar Serbia',
		'Rubel Rusia',
		'Riyal Arab Saudi',
		'Dolar Kepulauan Solomon',
		'Rupee Seychelles',
		'Krona Swedia',
		'Dolar Singapura',
		'Pound Saint Helena',
		'Shilling Somalia',
		'Dolar Suriname',
		'Kolon El Salvador',
		'Pound Suriah',
		'Baht Thailand',
		'Lira Turki',
		'Dolar Trinidad dan Tobago',
		'Dolar Tuvalu',
		'Dolar Baru Taiwan',
		'Ukraina Ukraina',
		'Dolar Amerika Serikat',
		'Peso Uruguay',
		'Som Uzbekistan',
		'Bolivar Venezuela',
		'Dong Vietnam',
		'Dolar Karibia Timur',
		'Rial Yaman',
		'Rand Afrika Selatan',
		'Dolar Zimbabwe'
	],
};

export const run = async ({ db }: SeedContext) => {
	const rows = Object.entries(daftar).flatMap(([nama, items]) =>
		items.map((item, index) => ({ daftar: nama, urutan: index + 1, nama: item }))
	);

	await batchInsert(
		db,
		rows.map((row) =>
			db
				.insert(referensi_lampiran_spt_pph_orang_pribadi)
				.values({ id: `ref-op-${row.daftar}-${row.urutan}`, ...row })
				.onConflictDoUpdate({
					target: [
						referensi_lampiran_spt_pph_orang_pribadi.daftar,
						referensi_lampiran_spt_pph_orang_pribadi.urutan
					],
					set: { nama: row.nama, aktif: true }
				})
		)
	);

	await db
		.update(referensi_lampiran_spt_pph_orang_pribadi)
		.set({ aktif: false })
		.where(notInArray(referensi_lampiran_spt_pph_orang_pribadi.daftar, Object.keys(daftar)));

	console.log(
		`Seeded SPT PPh Orang Pribadi lampiran references: ${rows.length} options across ${Object.keys(daftar).length} lists`
	);

	return [];
};
