import { notInArray } from 'drizzle-orm';
import { referensi_lampiran_spt_pph_orang_pribadi } from '../../schema';
import type { SeedContext } from '../context';
import { batchInsert } from '../helpers';

export const name = '016 SPT PPh Orang Pribadi lampiran reference lists';

// Transcribed from the live Coretax dropdowns, captured in
// docs/ui-reference/coretax/spt-1770-lampiran/REFERENCE-LISTS.txt.
//
// Only descriptions are stored: our KODE fields are plain text the peserta
// types, so the lists do not need code/description pairs. Order is DJP's own and
// is preserved verbatim, including the duplicates and non-country entries in the
// negara list (Angola and Jersey each appear twice). Do not sort or dedupe.
//
// These are the 13 lists the L-1 lampiran needs. The remaining 7 (L-2, L-3A-4
// and L-5) are in the same source file and can be added the same way.
const daftar: Record<string, readonly string[]> = {
	l1_a1_deskripsi: [
		'Uang Tunai/Bank Note/Koin',
		'Tabungan (Bank/Lembaga Keuangan)',
		'Giro',
		'Deposito',
		'Uang elektronik',
		'Cek',
		'Wessel',
		'Commercial Paper',
		'Setara Kas Lainnya'
	],
	negara: [
		'Aruba',
		'Afganistan',
		'Angola',
		'Angola',
		'Kepulauan Aland',
		'Albania',
		'Andorra',
		'Uni Emirat Arab',
		'Argentina',
		'Armenia',
		'Samoa Amerika',
		'Antartika',
		'Wilayah Selatan Prancis',
		'Antigua dan Barbuda',
		'Australia',
		'Austria',
		'Azerbaijan',
		'Burundi',
		'Belgia',
		'Benin',
		'Bonaire, Sint Eustatius dan Saba',
		'Burkina Faso',
		'Bangladesh',
		'Bulgaria',
		'Bahrain',
		'Bahama',
		'Bosnia dan Herzegovina',
		'Santo Barthelemy',
		'Belarusia',
		'Belize',
		'Bermuda',
		'Negara Majemuk Bolivia',
		'Brasil',
		'Barbados',
		'Brunei Darussalam',
		'Bhutan',
		'Pulau Bouvet',
		'Botswana',
		'Republik Afrika Tengah',
		'Kanada',
		'Kepulauan Cocos (Keeling)',
		'Swiss',
		'Cile',
		'Tiongkok',
		'Pantai Gading',
		'Kamerun',
		'Republik Demokratik Kongo',
		'Kongo',
		'Kepulauan Cook',
		'Kolombia',
		'Komoro',
		'Cabo Verde',
		'Kosta Rika',
		'Kuba',
		'Curacao',
		'Pulau Natal',
		'Kepulauan Cayman',
		'Siprus',
		'Republik Ceko',
		'Jerman',
		'Djibouti',
		'Dominika',
		'Denmark',
		'Republik Dominika',
		'Aljazair',
		'Ekuador',
		'Mesir',
		'Eritrea',
		'Sahara Barat',
		'Spanyol',
		'Estonia',
		'Etiopia',
		'Finlandia',
		'Fiji',
		'Kepulauan Falkland (Malvinas)',
		'Prancis',
		'Kepulauan Faroe',
		'Negara Federasi Mikronesia',
		'Gabon',
		'Britania Raya',
		'Georgia',
		'Guernsey',
		'Ghana',
		'Gibraltar',
		'Guinea',
		'Guadeloupe',
		'Gambia',
		'Guinea-Bissau',
		'Ekuator Guinea',
		'Yunani',
		'Granada',
		'Greenland',
		'Georgia Selatan dan Kepulauan Sandwich Selatan',
		'Guatemala',
		'Guyana Prancis',
		'Guam',
		'Guyana',
		'Hongkong',
		'Pulau Heard dan Kepulauan McDonald',
		'Honduras',
		'Kroasia',
		'Haiti',
		'Hongaria',
		'Indonesia',
		'Pulau Man',
		'India',
		'Wilayah Samudra Hindia Britania',
		'Irlandia',
		'Republik Islam Iran',
		'Irak',
		'Islandia',
		'Israel',
		'Italia',
		'Jamaika',
		'Jersey',
		'Jersey',
		'Yordania',
		'Jepang',
		'Kazakstan',
		'Kenya',
		'Kirgistan',
		'Kamboja',
		'Kiribati',
		'Saint Kitts dan Nevis',
		'Korea (Republik)',
		'Kosovo',
		'KOREA (STH), REPUBLIC',
		'KOREA (NTH) - DEMOCRATIC PEOPLES',
		'Kuwait',
		'Republik Demokratik Rakyat Laos',
		'Libanon',
		'Liberia',
		'Libya',
		'Santa Lucia',
		'Liechtenstein',
		'Tanpa kewarganegaraan',
		'Sri Lanka',
		'Lesoto',
		'Lithuania',
		'Luksemburg',
		'Latvia',
		'Makao',
		'Santo Martin (bagian Prancis)',
		'Maroko',
		'Monako',
		'Republik Moldova',
		'Madagaskar',
		'Maladewa',
		'Meksiko',
		'Kepulauan Marshall',
		'Republik Makedonia Bekas Yugoslavia',
		'Mali',
		'Malta',
		'Myanmar',
		'Montenegro',
		'Mongolia',
		'Kepulauan Mariana Utara',
		'Mozambik',
		'Mauritania',
		'Montserrat',
		'Martinik',
		'Mauritius',
		'Malawi',
		'Malaysia',
		'Namibia',
		'Kaledonia Baru',
		'Niger',
		'Pulau Norfolk',
		'Nigeria',
		'Nikaragua',
		'Niue',
		'Belanda',
		'Belanda - Kerajaan',
		'Norwegia',
		'Nepal',
		'Nauru',
		'Selandia Baru',
		'Oman',
		'Pakistan',
		'Panama',
		'UNITED NATIONS AGENCY',
		'Pitcairn',
		'Peru',
		'Filipina',
		'Palau',
		'Papua Nugini',
		'Polandia',
		'Perancis',
		'Puerto Riko',
		'Republik Rakyat Demokratik Korea',
		'Portugal',
		'Paraguay',
		'Negara Palestina',
		'PALESTINE',
		'Polinesia',
		'Qatar',
		'Reuni',
		'Pengungsi (Konvensi Pasal 1, 1951)',
		'Republik Irlandia',
		'Rumania (New Code)',
		'Rumania',
		'Federasi Rusia',
		'Rwanda',
		'Arab Saudi',
		'Pulau Solomon',
		'Sudan',
		'Senegal',
		'Singapura',
		'Saint Helena, Ascension dan Tristan da Cunha',
		'Svalbard dan Jan Mayen',
		'Sierra Leone',
		'El Salvador',
		'San Marino',
		'Somalia',
		'Saint Pierre dan Miquelon',
		'Serbia',
		'Sudan Selatan',
		'Sao Tome dan Principe',
		'Suriname',
		'Slowakia',
		'Slovenia',
		'SLOVAK REPUBLIC',
		'SWAZILAND',
		'Swedia',
		'Eswatini',
		'Sint Maarten (bagian Belanda)',
		'Seychelles',
		'Republik Arab Suriah',
		'Kepulauan Turks dan Caicos',
		'Chad',
		'Togo',
		'Thailand',
		'Tajikistan',
		'Tokelau',
		'Turkmenistan',
		'Timor Leste',
		'TIMOR LESTE DEMOCRATIC REPUBLIC',
		'Tonga',
		'Trinidad dan Tobago',
		'Tunisia',
		'Turki',
		'Tuvalu',
		'TAIWAN - PROVINCE OF CHINA',
		'Taiwan',
		'Tanzania, Republik Bersatu',
		'Uganda',
		'Ukraina',
		'Kepulauan Terpencil Kecil Amerika Serikat',
		'Uruguay',
		'Amerika Serikat',
		'Uzbekistan',
		'Tahta Suci (Negara Kota Vatikan)',
		'Saint Vincent dan Grenadines',
		'Venezuela (Republik Bolivarian)',
		'Kepulauan Virgin (Inggris)',
		'Kepulauan Virgin (Amerika Serikat)',
		'Vietnam',
		'Vanuatu',
		'Wallis dan Futuna',
		'Samoa',
		'Yaman',
		'Mayotte',
		'Afrika Selatan',
		'Zambia',
		'Zimbabwe'
	],
	keterangan_pps: [
		'Harta PPS',
		'Harta Investasi PPS'
	],
	l1_a2_deskripsi: [
		'Piutang Usaha',
		'Piutang Afiliasi',
		'Piutang lainnya'
	],
	l1_a3_deskripsi: [
		'Saham yang dibeli untuk dijual kembali',
		'Saham non bursa',
		'Saham bursa',
		'Obligasi perusahaan',
		'Obligasi pemerintah Indonesia (Obligasi Ritel Indonesia, Surat Berharga Syariah Negara, dll)',
		'Surat Utang lainnya',
		'Kontrak Investasi Kolektif (KIK) termasuk Reksadana, dan investasi yang dikonversikan ke unit..',
		'Instrumen derivatif (right, warran, kontrak berjangka, opsi, dll)',
		'Penyertaan modal dalam perusahaan lain yang bukan atas saham meliputi penyertaan modal pada C..',
		'Asuransi',
		'Unit Link di Asuransi',
		'Investasi lainnya (termasuk Cryptocurrency, Trust Fund dan Investasi lainnya)'
	],
	l1_a4_tipe: [
		'Sepeda',
		'Sepeda Motor',
		'Mobil Penumpang',
		'Bis',
		'Kendaraan Angkutan Jalan',
		'Kendaraan Tujuan Khusus',
		'Kereta',
		'Pesawat Terbang',
		'Kapal',
		'Mesin',
		'Gerobak',
		'Kapal Pesiar',
		'Harta bergerak lainnya'
	],
	l1_a4_kepemilikan: [
		'Atas nama pihak lain',
		'Atas nama sendiri'
	],
	l1_a5_deskripsi: [
		'Tanah Kosong',
		'Tanah dan/atau Bangunan untuk Tempat Tinggal',
		'Apartemen',
		'Kapal',
		'Tanah atau Lahan untuk Usaha (seperti lahan pertanian, perkebunan, perikanan darat, dan sejen..',
		'Tanah dan/atau Bangunan untuk Usaha (toko, pabrik, gudang, dan sejenisnya)',
		'Tanah dan/atau Bangunan yang Disewakan',
		'Harta Tidak Bergerak Lainnya'
	],
	l1_a5_sumber_kepemilikan: [
		'Utang',
		'Hadiah',
		'Hibah',
		'Warisan',
		'Sumber lainnya',
		'Hasil Sendiri'
	],
	l1_a6_deskripsi: [
		'Paten',
		'Royalti',
		'Merek dagang',
		'Harta Tidak Berwujud Lainnya',
		'Emas Batangan',
		'Emas Perhiasan',
		'Batangan Non-Emas',
		'Perhiasan Non-Emas',
		'Permata (intan,berlian,batu mulia lainnya)',
		'Barang-barang seni dan antik (barang-barang seni, barang-barang antik)',
		'Peralatan olahraga khusus',
		'Peralatan elektronik',
		'Perabot Rumah Tangga',
		'Peralatan Kantor',
		'Jet Ski',
		'Persediaan usaha',
		'Harta lainnya'
	],
	l1_b_deskripsi: [
		'Utang Bank / Lembaga Keuangan Bukan Bank (KPR, Leasing Kendaraan Bermotor, dan sejenisnya)',
		'Kartu Kredit',
		'Utang Afiliasi (Pinjaman dari pihak yang memiliki hubungan istimewa sebagaimana dimaksud dala..',
		'Utang Lainnya'
	],
	l1_b_keterangan: [
		'Debt in relation to Voluntary Disclosure Program Assets/Utang terkait PPS'
	],
	l1_e_jenis_pajak: [
		'PPh Pasal 15',
		'PPh Pasal 21',
		'PPh Pasal 22',
		'PPh Pasal 23',
		'PPh Pasal 26',
		'PPh Ditanggung Pemerintah',
		'PPh Ditanggung Pemerintah(Proyek Bantuan Luar Negeri)',
		'Nilai LB dalam SPT yang dianggap bukan merupakan lebih bayar'
	],
};

export const run = async ({ db }: SeedContext) => {
	const rows = Object.entries(daftar).flatMap(([nama, items]) =>
		items.map((item, index) => ({ daftar: nama, urutan: index + 1, nama: item }))
	);

	await batchInsert(
		db,
		rows.map((row) =>
			db
				.insert(referensi_lampiran_spt_pph_orang_pribadi)
				.values({ id: `ref-op-${row.daftar}-${row.urutan}`, ...row })
				.onConflictDoUpdate({
					target: [
						referensi_lampiran_spt_pph_orang_pribadi.daftar,
						referensi_lampiran_spt_pph_orang_pribadi.urutan
					],
					set: { nama: row.nama, aktif: true }
				})
		)
	);

	await db
		.update(referensi_lampiran_spt_pph_orang_pribadi)
		.set({ aktif: false })
		.where(notInArray(referensi_lampiran_spt_pph_orang_pribadi.daftar, Object.keys(daftar)));

	console.log(
		`Seeded SPT PPh Orang Pribadi lampiran references: ${rows.length} options across ${Object.keys(daftar).length} lists`
	);

	return [];
};
