import { notInArray } from 'drizzle-orm';
import { referensi_lampiran_spt_pph_orang_pribadi } from '../../schema';
import type { SeedContext } from '../context';
import { batchInsert } from '../helpers';

export const name = '016 SPT PPh Orang Pribadi lampiran reference lists';

// Originally transcribed from the live Coretax dropdowns, captured in
// docs/ui-reference/coretax/spt-1770-lampiran/REFERENCE-LISTS.txt, then
// reconciled against the reference-data endpoint
// (docs/coretax-api/reference-data-1770.json).
//
// An entry is either a bare description or a [kode, deskripsi] pair. 19 of the
// 20 lists carry codes; the endpoint is the only source for the codes Coretax
// derives its disabled KODE cells from. The exception is l2_c_jenis_penghasilan
// -- a sweep of all 416 populated reference types found none that covers it, and
// none even close to its 29 options, so its KODE stays blank.
//
// Codes were matched to options BY DESCRIPTION, not by position: the endpoint
// returns each list in its own order, unrelated to the display order below. The
// match is case-insensitive and tolerates the UI capture's clipped text, which
// repaired 78 descriptions that had been stored truncated mid-word; the full
// text here is DJP's own.
//
// Order is DJP's own and is preserved verbatim, including the duplicates and
// non-country entries in the negara list. Do not sort or dedupe.
//
// The negara duplicates are DJP's own: COUNTRY_CODE itself lists "Angola" twice
// (AGO and AIA -- AIA is really Anguilla) and "Jersey" twice (JEY and JE). Which
// of our two rows should take which code is NOT determinable, since the two
// descriptions are identical; the assignment below is arbitrary and should not
// be read as verified. It is harmless today because no KODE cell derives from
// the negara list, and a description-keyed lookup collapses the pair anyway.
//
// All 20 lists in the source file: L-1 (13), L-2 (4: L-2 A/B/C + shared Mata
// Uang), L-3A-4 B, and L-5 B/C.
//
// The eight l3c_*/l3d_* lists were added later, when those lampiran were built.
// They come straight from the reference endpoint and were never captured from
// the UI, because neither lampiran was reachable on the captured account. Their
// DISPLAY order is therefore unknown -- the order here is the endpoint's own,
// which for every list we could check is NOT the order Coretax renders. Treat
// the ordering of these eight as unverified; their contents and codes are exact.
type Opsi = string | readonly [kode: string, deskripsi: string];

const daftar: Record<string, readonly Opsi[]> = {
	l1_a1_deskripsi: [
		['0101', 'Uang Tunai/Bank Note/Koin'],
		['0102', 'Tabungan (Bank/Lembaga Keuangan)'],
		['0103', 'Giro'],
		['0104', 'Deposito'],
		['0105', 'Uang elektronik'],
		['0106', 'Cek'],
		['0107', 'Wessel'],
		['0108', 'Commercial Paper'],
		['0109', 'Setara Kas Lainnya']
	],
	negara: [
		['ABW', 'Aruba'],
		['AFG', 'Afganistan'],
		['AGO', 'Angola'],
		['AIA', 'Angola'],
		['ALA', 'Kepulauan Aland'],
		['ALB', 'Albania'],
		['AND', 'Andorra'],
		['ARE', 'Uni Emirat Arab'],
		['ARG', 'Argentina'],
		['ARM', 'Armenia'],
		['ASM', 'Samoa Amerika'],
		['ATA', 'Antartika'],
		['ATF', 'Wilayah Selatan Prancis'],
		['ATG', 'Antigua dan Barbuda'],
		['AUS', 'Australia'],
		['AUT', 'Austria'],
		['AZE', 'Azerbaijan'],
		['BDI', 'Burundi'],
		['BEL', 'Belgia'],
		['BEN', 'Benin'],
		['BES', 'Bonaire, Sint Eustatius dan Saba'],
		['BFA', 'Burkina Faso'],
		['BGD', 'Bangladesh'],
		['BGR', 'Bulgaria'],
		['BHR', 'Bahrain'],
		['BHS', 'Bahama'],
		['BIH', 'Bosnia dan Herzegovina'],
		['BLM', 'Santo Barthelemy'],
		['BLR', 'Belarusia'],
		['BLZ', 'Belize'],
		['BMU', 'Bermuda'],
		['BOL', 'Negara Majemuk Bolivia'],
		['BRA', 'Brasil'],
		['BRB', 'Barbados'],
		['BRN', 'Brunei Darussalam'],
		['BTN', 'Bhutan'],
		['BVT', 'Pulau Bouvet'],
		['BWA', 'Botswana'],
		['CAF', 'Republik Afrika Tengah'],
		['CAN', 'Kanada'],
		['CCK', 'Kepulauan Cocos (Keeling)'],
		['CHE', 'Swiss'],
		['CHL', 'Cile'],
		['CHN', 'Tiongkok'],
		['CIV', 'Pantai Gading'],
		['CMR', 'Kamerun'],
		['COD', 'Republik Demokratik Kongo'],
		['COG', 'Kongo'],
		['COK', 'Kepulauan Cook'],
		['COL', 'Kolombia'],
		['COM', 'Komoro'],
		['CPV', 'Cabo Verde'],
		['CRI', 'Kosta Rika'],
		['CUB', 'Kuba'],
		['CUW', 'Curacao'],
		['CXR', 'Pulau Natal'],
		['CYM', 'Kepulauan Cayman'],
		['CYP', 'Siprus'],
		['CZE', 'Republik Ceko'],
		['DEU', 'Jerman'],
		['DJI', 'Djibouti'],
		['DMA', 'Dominika'],
		['DNK', 'Denmark'],
		['DOM', 'Republik Dominika'],
		['DZA', 'Aljazair'],
		['ECU', 'Ekuador'],
		['EGY', 'Mesir'],
		['ERI', 'Eritrea'],
		['ESH', 'Sahara Barat'],
		['ESP', 'Spanyol'],
		['EST', 'Estonia'],
		['ETH', 'Etiopia'],
		['FIN', 'Finlandia'],
		['FJ', 'Fiji'],
		['FLK', 'Kepulauan Falkland (Malvinas)'],
		['FRA', 'Prancis'],
		['FRO', 'Kepulauan Faroe'],
		['FSM', 'Negara Federasi Mikronesia'],
		['GAB', 'Gabon'],
		['GBR', 'Britania Raya'],
		['GEO', 'Georgia'],
		['GGY', 'Guernsey'],
		['GHA', 'Ghana'],
		['GIB', 'Gibraltar'],
		['GIN', 'Guinea'],
		['GLP', 'Guadeloupe'],
		['GMB', 'Gambia'],
		['GNB', 'Guinea-Bissau'],
		['GQ', 'Ekuator Guinea'],
		['GRC', 'Yunani'],
		['GRD', 'Granada'],
		['GRL', 'Greenland'],
		['GS', 'Georgia Selatan dan Kepulauan Sandwich Selatan'],
		['GTM', 'Guatemala'],
		['GUF', 'Guyana Prancis'],
		['GUM', 'Guam'],
		['GUY', 'Guyana'],
		['HKG', 'Hongkong'],
		['HMD', 'Pulau Heard dan Kepulauan McDonald'],
		['HND', 'Honduras'],
		['HRV', 'Kroasia'],
		['HTI', 'Haiti'],
		['HUN', 'Hongaria'],
		['IDN', 'Indonesia'],
		['IM', 'Pulau Man'],
		['IND', 'India'],
		['IOT', 'Wilayah Samudra Hindia Britania'],
		['IRL', 'Irlandia'],
		['IRN', 'Republik Islam Iran'],
		['IRQ', 'Irak'],
		['ISL', 'Islandia'],
		['ISR', 'Israel'],
		['ITA', 'Italia'],
		['JAM', 'Jamaika'],
		['JEY', 'Jersey'],
		['JE', 'Jersey'],
		['JOR', 'Yordania'],
		['JPN', 'Jepang'],
		['KAZ', 'Kazakstan'],
		['KEN', 'Kenya'],
		['KGZ', 'Kirgistan'],
		['KHM', 'Kamboja'],
		['KI', 'Kiribati'],
		['KNA', 'Saint Kitts dan Nevis'],
		['KOR', 'Korea (Republik)'],
		['KR', 'Kosovo'],
		['KRS', 'KOREA (STH), REPUBLIC'],
		['KRU', 'KOREA (NTH) - DEMOCRATIC PEOPLES'],
		['KWT', 'Kuwait'],
		['LAO', 'Republik Demokratik Rakyat Laos'],
		['LBN', 'Libanon'],
		['LBR', 'Liberia'],
		['LBY', 'Libya'],
		['LCA', 'Santa Lucia'],
		['LIE', 'Liechtenstein'],
		['LK', 'Tanpa kewarganegaraan'],
		['LKA', 'Sri Lanka'],
		['LSO', 'Lesoto'],
		['LTU', 'Lithuania'],
		['LUX', 'Luksemburg'],
		['LVA', 'Latvia'],
		['MAC', 'Makao'],
		['MAF', 'Santo Martin (bagian Prancis)'],
		['MAR', 'Maroko'],
		['MCO', 'Monako'],
		['MDA', 'Republik Moldova'],
		['MDG', 'Madagaskar'],
		['MDV', 'Maladewa'],
		['MEX', 'Meksiko'],
		['MHL', 'Kepulauan Marshall'],
		['MK', 'Republik Makedonia Bekas Yugoslavia'],
		['MLI', 'Mali'],
		['MLT', 'Malta'],
		['MM', 'Myanmar'],
		['MNE', 'Montenegro'],
		['MNG', 'Mongolia'],
		['MNP', 'Kepulauan Mariana Utara'],
		['MOZ', 'Mozambik'],
		['MRT', 'Mauritania'],
		['MSR', 'Montserrat'],
		['MTQ', 'Martinik'],
		['MUS', 'Mauritius'],
		['MWI', 'Malawi'],
		['MYS', 'Malaysia'],
		['NAM', 'Namibia'],
		['NCL', 'Kaledonia Baru'],
		['NER', 'Niger'],
		['NFK', 'Pulau Norfolk'],
		['NGA', 'Nigeria'],
		['NIC', 'Nikaragua'],
		['NIU', 'Niue'],
		['NLD', 'Belanda'],
		['NLK', 'Belanda - Kerajaan'],
		['NOR', 'Norwegia'],
		['NPL', 'Nepal'],
		['NRU', 'Nauru'],
		['NZL', 'Selandia Baru'],
		['OMN', 'Oman'],
		['PAK', 'Pakistan'],
		['PAN', 'Panama'],
		['PBB', 'UNITED NATIONS AGENCY'],
		['PCN', 'Pitcairn'],
		['PER', 'Peru'],
		['PHL', 'Filipina'],
		['PLW', 'Palau'],
		['PNG', 'Papua Nugini'],
		['POL', 'Polandia'],
		['PRA', 'Perancis'],
		['PRI', 'Puerto Riko'],
		['PRK', 'Republik Rakyat Demokratik Korea'],
		['PRT', 'Portugal'],
		['PRY', 'Paraguay'],
		['PS', 'Negara Palestina'],
		['PSE', 'PALESTINE'],
		['PYF', 'Polinesia'],
		['QAT', 'Qatar'],
		['REU', 'Reuni'],
		['RFG', 'Pengungsi (Konvensi Pasal 1, 1951)'],
		['RIL', 'Republik Irlandia'],
		['ROM', 'Rumania (New Code)'],
		['ROU', 'Rumania'],
		['RUS', 'Federasi Rusia'],
		['RWA', 'Rwanda'],
		['SAU', 'Arab Saudi'],
		['SB', 'Pulau Solomon'],
		['SDN', 'Sudan'],
		['SEN', 'Senegal'],
		['SGP', 'Singapura'],
		['SHN', 'Saint Helena, Ascension dan Tristan da Cunha'],
		['SJM', 'Svalbard dan Jan Mayen'],
		['SLE', 'Sierra Leone'],
		['SLV', 'El Salvador'],
		['SMR', 'San Marino'],
		['SOM', 'Somalia'],
		['SPM', 'Saint Pierre dan Miquelon'],
		['SRB', 'Serbia'],
		['SSD', 'Sudan Selatan'],
		['STP', 'Sao Tome dan Principe'],
		['SUR', 'Suriname'],
		['SVK', 'Slowakia'],
		['SVN', 'Slovenia'],
		['SVR', 'SLOVAK REPUBLIC'],
		['SWA', 'SWAZILAND'],
		['SWE', 'Swedia'],
		['SWZ', 'Eswatini'],
		['SXM', 'Sint Maarten (bagian Belanda)'],
		['SYC', 'Seychelles'],
		['SYR', 'Republik Arab Suriah'],
		['TCA', 'Kepulauan Turks dan Caicos'],
		['TCD', 'Chad'],
		['TGO', 'Togo'],
		['THA', 'Thailand'],
		['TJK', 'Tajikistan'],
		['TKL', 'Tokelau'],
		['TKM', 'Turkmenistan'],
		['TLS', 'Timor Leste'],
		['TLT', 'TIMOR LESTE DEMOCRATIC REPUBLIC'],
		['TON', 'Tonga'],
		['TTO', 'Trinidad dan Tobago'],
		['TUN', 'Tunisia'],
		['TUR', 'Turki'],
		['TUV', 'Tuvalu'],
		['TWA', 'TAIWAN - PROVINCE OF CHINA'],
		['TWN', 'Taiwan'],
		['TZ', 'Tanzania, Republik Bersatu'],
		['UGA', 'Uganda'],
		['UKR', 'Ukraina'],
		['UMI', 'Kepulauan Terpencil Kecil Amerika Serikat'],
		['URY', 'Uruguay'],
		['USA', 'Amerika Serikat'],
		['UZB', 'Uzbekistan'],
		['VAT', 'Tahta Suci (Negara Kota Vatikan)'],
		['VCT', 'Saint Vincent dan Grenadines'],
		['VEN', 'Venezuela (Republik Bolivarian)'],
		['VGB', 'Kepulauan Virgin (Inggris)'],
		['VIR', 'Kepulauan Virgin (Amerika Serikat)'],
		['VNM', 'Vietnam'],
		['VUT', 'Vanuatu'],
		['WLF', 'Wallis dan Futuna'],
		['WS', 'Samoa'],
		['YEM', 'Yaman'],
		['YT', 'Mayotte'],
		['ZAF', 'Afrika Selatan'],
		['ZMB', 'Zambia'],
		['ZWE', 'Zimbabwe']
	],
	keterangan_pps: [
		['01', 'Harta PPS'],
		['02', 'Harta Investasi PPS']
	],
	l1_a2_deskripsi: [
		['0201', 'Piutang Usaha'],
		['0202', 'Piutang Afiliasi'],
		['0209', 'Piutang lainnya']
	],
	l1_a3_deskripsi: [
		['0301', 'Saham yang dibeli untuk dijual kembali'],
		['0302', 'Saham non bursa'],
		['0303', 'Saham bursa'],
		['0304', 'Obligasi perusahaan'],
		['0305', 'Obligasi pemerintah Indonesia (Obligasi Ritel Indonesia, Surat Berharga Syariah Negara, dll)'],
		['0306', 'Surat Utang lainnya'],
		['0307', 'Kontrak Investasi Kolektif (KIK) termasuk Reksadana, dan investasi yang dikonversikan ke unit penyertaan'],
		['0308', 'Instrumen derivatif (right, warran, kontrak berjangka, opsi, dll)'],
		['0309', 'Penyertaan modal dalam perusahaan lain yang bukan atas saham meliputi penyertaan modal pada CV, Firma, dan sejenisnya'],
		['0310', 'Asuransi'],
		['0311', 'Unit Link di Asuransi'],
		['0399', 'Investasi lainnya (termasuk Cryptocurrency, Trust Fund dan Investasi lainnya)']
	],
	l1_a4_tipe: [
		['0401', 'Sepeda'],
		['0402', 'Sepeda Motor'],
		['0403', 'Mobil Penumpang'],
		['0404', 'Bis'],
		['0405', 'Kendaraan Angkutan Jalan'],
		['0406', 'Kendaraan Tujuan Khusus'],
		['0407', 'Kereta'],
		['0408', 'Pesawat Terbang'],
		['0409', 'Kapal'],
		['0410', 'Mesin'],
		['0411', 'Gerobak'],
		['0412', 'Kapal Pesiar'],
		['0499', 'Harta bergerak lainnya']
	],
	l1_a4_kepemilikan: [
		['OTHER', 'Atas nama pihak lain'],
		['TAXPAYER', 'Atas nama sendiri']
	],
	l1_a5_deskripsi: [
		['0501', 'Tanah Kosong'],
		['0502', 'Tanah dan/atau Bangunan untuk Tempat Tinggal'],
		['0503', 'Apartemen'],
		['0504', 'Kapal'],
		['0505', 'Tanah atau Lahan untuk Usaha (seperti lahan pertanian, perkebunan, perikanan darat, dan sejenisnya)'],
		['0506', 'Tanah dan/atau Bangunan untuk Usaha (toko, pabrik, gudang, dan sejenisnya)'],
		['0507', 'Tanah dan/atau Bangunan yang Disewakan'],
		['0509', 'Harta Tidak Bergerak Lainnya']
	],
	l1_a5_sumber_kepemilikan: [
		['DEBT', 'Utang'],
		['GIFT', 'Hadiah'],
		['GRANT', 'Hibah'],
		['INHERITANCE', 'Warisan'],
		['OTHERSOURCES', 'Sumber lainnya'],
		['OWN', 'Hasil Sendiri']
	],
	l1_a6_deskripsi: [
		['0601', 'Paten'],
		['0602', 'Royalti'],
		['0603', 'Merek dagang'],
		['0699', 'Harta Tidak Berwujud Lainnya'],
		['0701', 'Emas Batangan'],
		['0702', 'Emas Perhiasan'],
		['0703', 'Batangan Non-Emas'],
		['0704', 'Perhiasan Non-Emas'],
		['0705', 'Permata (intan,berlian,batu mulia lainnya)'],
		['0706', 'Barang-barang seni dan antik (barang-barang seni, barang-barang antik)'],
		['0707', 'Peralatan olahraga khusus'],
		['0708', 'Peralatan elektronik'],
		['0709', 'Perabot Rumah Tangga'],
		['0710', 'Peralatan Kantor'],
		['0711', 'Jet Ski'],
		['0712', 'Persediaan usaha'],
		['0799', 'Harta lainnya']
	],
	l1_b_deskripsi: [
		['101', 'Utang Bank / Lembaga Keuangan Bukan Bank (KPR, Leasing Kendaraan Bermotor, dan sejenisnya)'],
		['102', 'Kartu Kredit'],
		['103', 'Utang Afiliasi (Pinjaman dari pihak yang memiliki hubungan istimewa sebagaimana dimaksud dalam Pasal 18 ayat (4) Undang-Undang PPh)'],
		['109', 'Utang Lainnya']
	],
	l1_b_keterangan: [
		['1', 'Debt in relation to Voluntary Disclosure Program Assets/Utang terkait PPS']
	],
	l1_e_jenis_pajak: [
		['ARTICLE15', 'PPh Pasal 15'],
		['ARTICLE21', 'PPh Pasal 21'],
		['ARTICLE22', 'PPh Pasal 22'],
		['ARTICLE23', 'PPh Pasal 23'],
		['ARTICLE26', 'PPh Pasal 26'],
		['BORNEBYGOVERNMENT', 'PPh Ditanggung Pemerintah'],
		['BORNEBYGOVERNMENTFOREIGNAID', 'PPh Ditanggung Pemerintah(Proyek Bantuan Luar Negeri)'],
		['EXCESSOVERPAYMENT', 'Nilai LB dalam SPT yang dianggap bukan merupakan lebih bayar']
	],
	l2_a_jenis_penghasilan: [
		['21-100-27', 'Upah Pegawai Tidak Tetap yang Dibayarkan secara Bulanan yang Mendapat Fasilitas di Daerah Tertentu'],
		['21-100-28', 'Imbalan kepada Bukan Pegawai Lainnya yang mendapat fasilitas di daerah tertentu'],
		['21-100-31', 'Upah Pegawai Tidak Tetap yang Dibayarkan secara Harian, Mingguan, Satuan dan Borongan dengan Penghasilan Bruto lebih dari Rp2.500.000 Sehari yang Mendapat Fasilitas di Daerah Tertentu'],
		['21-100-29', 'Upah Pegawai Tidak Tetap yang Dibayarkan secara Harian, Mingguan, Satuan dan Borongan dengan Penghasilan Bruto sampai dengan Rp2.500.000 Sehari yang Mendapat Fasilitas di Daerah Tertentu'],
		['21-100-32', 'Penghasilan yang Diterima atau Diperoleh Pegawai Tetap yang Menerima Fasilitas di Daerah Tertentu'],
		['21-401-01', 'Uang Pesangon yang Dibayarkan Sekaligus'],
		['21-401-02', 'Uang Manfaat Pensiun, Tunjangan Hari Tua atau Jaminan Hari Tua dan Pembayaran Sejenis yang Dibayarkan Sekaligus'],
		['21-402-01', 'Honor dan Imbalan Lain yang Dibebankan Dibebankan kepada APBN atau APBD yang Diterima oleh PNS, Anggota TNI/POLRI, Pejabat Negara dan Pensiunannya (LAMA)'],
		['21-402-02', 'Honor atau Imbalan Lain yang Dibebankan kepada APBN atau APBD yang Diterima oleh PNS Golongan III, Anggota TNI dan Anggota POLRI Golongan Pangkat Perwira Pertama, dan pensiunannya'],
		['21-402-03', 'Honor atau Imbalan Lain yang Dibebankan kepada APBN atau APBD yang Diterima oleh Pejabat Negara, PNS Golongan IV, Anggota TNI dan Anggota POLRI Golongan Pangkat Perwira Menengah dan Perwira Tinggi, dan Pensiunannya'],
		['21-402-04', 'Honor atau Imbalan Lain yang Dibebankan kepada APBN atau APBD yang Diterima oleh PNS Golongan I dan Golongan II, Anggota TNI dan Anggota POLRI Golongan Pangkat Tamtama dan Bintara, dan Pensiunannya'],
		['21-499-99', 'Objek PPh Pasal 21 yang Bersifat Final Lainnya'],
		['22-101-02', 'Penghasilan Sehubungan dengan Transaksi Penjualan Barang, Penyerahan Jasa, dan/atau Persewaan serta Penghasilan Lain Sehubungan dengan Penggunaan Harta yang Dilakukan Melalui Pihak Lain dalam Sistem Informasi Pengadaan Pemerintah (Final)'],
		['22-102-02', 'Penghasilan yang Diterima atau Diperoleh Pedagang Dalam Negeri Penjualan Barang, Penyerahan Jasa, dan/atau Persewaan serta Penghasilan Lain Sehubungan dengan Penggunaan Harta yang Dilakukan Melalui Perdagangan Melalui Sistem Elektronik (Final)'],
		['22-401-01', 'Penjualan BBM oleh Pertamina atau Anak Perusahaan Pertamina Kepada SPBU (Final)'],
		['22-401-02', 'Penjualan BBM oleh Badan Usaha Selain Pertamina atau Anak Perusahaan Pertamina Kepada SPBU/Agen/Penyalur  (Final)'],
		['22-401-03', 'Penjualan BBG oleh produsen/importir Kepada SPBU/Agen/Penyalur (Final)'],
		['22-401-04', 'Penjualan BBM oleh Pertamina atau Anak Perusahaan Pertamina kepada Agen/Penyalur selain SPBU (Final)'],
		['22-405-01', 'Penghasilan Sehubungan dengan Aset Kripto yang dipungut oleh Penyelenggara Perdagangan Melalui Sistem Elektronik yang Merupakan Pedagang Fisik Aset Kripto'],
		['22-405-02', 'Penghasilan Sehubungan dengan Aset Kripto yang dipungut oleh Penyelenggara Perdagangan Melalui Sistem Elektronik yang Bukan Merupakan Pedagang Fisik Aset Kripto'],
		['22-405-03', 'Penghasilan Sehubungan dengan Aset Kripto (Setor Sendiri)'],
		['22-405-05', 'Penghasilan Sehubungan dengan Aset Kripto yang dipungut oleh Penyelenggara Perdagangan Melalui Sistem Elektronik Luar Negeri yang Merupakan Pemungut Pajak Penghasilan'],
		['22-405-04', 'Penghasilan Sehubungan dengan Aset Kripto yang dipungut oleh Penyelenggara Perdagangan Melalui Sistem Elektronik Dalam Negeri yang Merupakan Pedagang Aset Keuangan Digital'],
		['22-405-07', 'Penghasilan Sehubungan dengan Transaksi Aset Kripto di Penyelenggara Perdagangan Melalui Sistem Elektronik Luar Negeri (Setor Sendiri) '],
		['22-405-06', 'Penghasilan Sehubungan dengan Transaksi Aset Kripto di Penyelenggara Perdagangan Melalui Sistem Elektronik Dalam Negeri (Setor Sendiri) '],
		['28-401-01', 'Bunga Obligasi, Surat Utang Negara, atau Obligasi Daerah yang Diterima Wajib Pajak Dalam Negeri dan Bentuk Usaha Tetap.'],
		['28-401-03', 'Bunga Obligasi yang Diterima Wajib Pajak Dalam Negeri dan Bentuk Usaha Tetap yang diadministrasikan oleh BI'],
		['28-401-04', 'Diskonto Surat Perbendaharaan Negara yang Diterima Wajib Pajak Dalam Negeri dan Bentuk Usaha Tetap'],
		['28-401-05', 'Diskonto Surat Perbendaharaan Negara yang Diterima Wajib Pajak Penduduk/Berkedudukan di Luar Negeri'],
		['28-401-06', 'Bunga Obligasi yang Diterima Wajib Pajak Dalam Negeri dan Bentuk Usaha Tetap'],
		['28-402-01', 'Pengalihan Hak atas Tanah dan/atau Bangunan'],
		['28-402-02', 'Pengalihan Rumah Sederhana dan Rumah Susun Sederhana yang Dilakukan oleh WP yang Usaha Pokoknya Mengalihkan Hak atas Tanah dan/atau Bangunan'],
		['28-402-03', 'Pengalihan Hak atas Tanah dan/atau Bangunan kepada Pemerintah, BUMN yang Mendapat Penugasan Khusus dari Pemerintah, atau BUMD yang Mendapat Penugasan Khusus dari Kepala Daerah, sesuai UU mengenai Pengadaan Tanah bagi Pembangunan untuk Kepentingan Umum'],
		['28-403-02', 'Persewaan Tanah dan/atau Bangunan'],
		['28-403-03', 'Kekurangan penyetoran PPh final dari pemungutan Pihak Lain (SIPP)-Persewaan Tanah dan/atau Bangunan'],
		['28-404-01', 'Bunga Tabungan dan Bunga Deposito yang Ditempatkan di Dalam Negeri yang Dananya Bersumber Selain dari Devisa Hasil Ekspor (DHE)'],
		['28-404-02', 'Bunga Deposito yang Ditempatkan di Dalam Negeri (mata uang IDR bersumber dari DHE tenor 1 bulan)'],
		['28-404-03', 'Bunga Deposito yang Ditempatkan di Dalam Negeri (mata uang IDR bersumber dari DHE tenor 3 bulan)'],
		['28-404-04', 'Bunga Deposito yang Ditempatkan di Dalam Negeri (mata uang IDR bersumber dari DHE tenor 6 bulan atau lebih)'],
		['28-404-05', 'Bunga Deposito yang Ditempatkan di Dalam Negeri (mata uang USD bersumber dari DHE tenor 1 bulan)'],
		['28-404-06', 'Bunga Deposito yang Ditempatkan di Dalam Negeri (mata uang USD bersumber dari DHE tenor 3 bulan)'],
		['28-404-07', 'Bunga Deposito yang Ditempatkan di Dalam Negeri (mata uang USD bersumber dari DHE tenor 6 bulan)'],
		['28-404-08', 'Bunga Deposito yang Ditempatkan di Dalam Negeri (mata uang USD bersumber dari DHE tenor lebih 6 bulan)'],
		['28-404-09', 'Bunga Deposito/Tabungan yang Ditempatkan di Luar Negeri Melalui Bank yang Didirikan atau Bertempat Kedudukan di Indonesia atau Cabang Bank Luar Negeri di Indonesia'],
		['28-404-10', 'Diskonto Sertifikat Bank Indonesia'],
		['28-404-11', 'Jasa Giro'],
		['28-405-01', 'Hadiah Undian'],
		['28-406-01', 'Transaksi Penjualan Saham di Bursa Efek (Bukan Saham Pendiri)'],
		['28-407-01', 'Transaksi Penjualan Saham di Bursa Efek (Saham Pendiri)'],
		['28-408-01', 'Transaksi Penjualan Saham Milik Perusahaan Modal Ventura Tidak di Bursa Efek'],
		['28-409-08', 'Jasa Konstruksi Berupa Jasa Perencanaan Konstruksi (Dengan Kualifikasi Usaha) yang Disetor Sendiri'],
		['28-409-09', 'Jasa Konstruksi Berupa Jasa Perencanaan Konstruksi (Tanpa Kualifikasi Usaha)'],
		['28-409-10', 'Jasa Konstruksi Berupa Jasa Pelaksanaan Konstruksi (Kualifikasi Usaha Kecil)'],
		['28-409-11', 'Jasa Konstruksi Berupa Jasa Pelaksanaan Konstruksi (Kualifikasi Usaha Menengah dan Besar)'],
		['28-409-12', 'Jasa Konstruksi Berupa Jasa Pelaksanaan Konstruksi (Tanpa Kualifikasi Usaha)'],
		['28-409-13', 'Jasa Konstruksi Berupa Jasa Pengawasan Konstruksi (Dengan Kualifikasi Usaha)'],
		['28-409-14', 'Jasa Konstruksi Berupa Jasa Pengawasan Konstruksi (Tanpa Kualifikasi Usaha)'],
		['28-409-22', 'Pekerjaan Konstruksi yang Dilakukan oleh Penyedia Jasa yang Memiliki Sertifikat Badan Usaha Kualifikasi Kecil atau Sertifikat Kompetensi Kerja untuk Usaha Orang Perseorangan'],
		['28-409-23', 'Pekerjaan Konstruksi yang Dilakukan oleh Penyedia Jasa yang Tidak Memiliki Sertifikat Badan Usaha Atau Sertifikat Kompetensi Kerja untuk Usaha Orang Perseorangan'],
		['28-409-24', 'Pekerjaan Konstruksi yang Dilakukan oleh Penyedia Jasa yang Memiliki Sertifikat Selain Sertifikat Badan Usaha Kualifikasi Kecil atau Sertifikat Kompetensi Kerja untuk Usaha Orang Perseorangan'],
		['28-409-25', 'Pekerjaan Konstruksi Terintegrasi yang Dilakukan oleh Penyedia Jasa yang Memiliki Sertifikat Badan Usaha'],
		['28-409-26', 'Pekerjaan Konstruksi Terintegrasi yang Dilakukan oleh Penyedia Jasa yang Tidak Memiliki Sertifikat Badan Usaha'],
		['28-409-27', 'Jasa Konsultansi Konstruksi yang Dilakukan oleh Penyedia Jasa yang Memiliki Sertifikat Badan Usaha atau Sertifikat Kompetensi Kerja untuk Usaha Orang Perseorangan'],
		['28-409-28', 'Jasa Konsultansi Konstruksi yang Dilakukan oleh Penyedia Jasa yang Tidak Memiliki Sertifikat Badan Usaha atau Sertifikat Kompetensi Kerja untuk Usaha Orang Perseorangan'],
		['28-409-30', 'Kekurangan penyetoran PPh final dari pemungutan Pihak Lain (SIPP)-Pekerjaan Konstruksi yang Dilakukan oleh Penyedia Jasa yang Tidak Memiliki Sertifikat Badan Usaha Atau Sertifikat Kompetensi Kerja untuk Usaha Orang Perseorangan (Disetor Sendiri)'],
		['28-409-29', 'Kekurangan penyetoran PPh final dari pemungutan Pihak Lain (SIPP)-Pekerjaan Konstruksi yang Dilakukan oleh Penyedia Jasa yang Memiliki Sertifikat Badan Usaha Kualifikasi Kecil atau Sertifikat Kompetensi Kerja untuk Usaha Orang Perseorangan (Disetor Sendiri)'],
		['28-409-31', 'Kekurangan penyetoran PPh final dari pemungutan Pihak Lain (SIPP)-Pekerjaan Konstruksi yang Dilakukan oleh Penyedia Jasa yang Memiliki Sertifikat Selain Sertifikat Badan Usaha Kualifikasi Kecil atau Sertifikat Kompetensi Kerja untuk Usaha Orang Perseorangan (Disetor Sendiri)'],
		['28-409-32', 'Kekurangan penyetoran PPh final dari pemungutan Pihak Lain (SIPP)-Pekerjaan Konstruksi Terintegrasi yang Dilakukan oleh Penyedia Jasa yang Memiliki Sertifikat Badan Usaha (Disetor Sendiri)'],
		['28-409-33', 'Kekurangan penyetoran PPh final dari pemungutan Pihak Lain (SIPP)-Pekerjaan Konstruksi Terintegrasi yang Dilakukan oleh Penyedia Jasa yang Tidak Memiliki Sertifikat Badan Usaha (Disetor Sendiri)'],
		['28-409-34', 'Kekurangan penyetoran PPh final dari pemungutan Pihak Lain (SIPP)-Jasa Konsultansi Konstruksi yang Dilakukan oleh Penyedia Jasa yang Memiliki Sertifikat Badan Usaha atau Sertifikat Kompetensi Kerja untuk Usaha Orang Perseorangan (Disetor Sendiri)'],
		['28-409-35', 'Kekurangan penyetoran PPh final dari pemungutan Pihak Lain (SIPP)-Jasa Konsultansi Konstruksi yang Dilakukan oleh Penyedia Jasa yang Tidak Memiliki Sertifikat Badan Usaha atau Sertifikat Kompetensi Kerja untuk Usaha Orang Perseorangan (Disetor Sendiri)'],
		['28-409-42', 'Kekurangan penyetoran PPh final dari pemungutan Pihak Lain (SIPP)-Jasa Konstruksi Berupa Jasa Pengawasan Konstruksi (Tanpa Kualifikasi Usaha) yang Disetor Sendiri'],
		['28-409-37', 'Kekurangan penyetoran PPh final dari pemungutan Pihak Lain (SIPP)-Jasa Konstruksi Berupa Jasa Perencanaan Konstruksi (Tanpa Kualifikasi Usaha) yang Disetor Sendiri'],
		['28-409-38', 'Kekurangan penyetoran PPh final dari pemungutan Pihak Lain (SIPP)-Jasa Konstruksi Berupa Jasa Pelaksanaan Konstruksi (Kualifikasi Usaha Kecil) yang Disetor Sendiri'],
		['28-409-40', 'Kekurangan penyetoran PPh final dari pemungutan Pihak Lain (SIPP)-Jasa Konstruksi Berupa Jasa Pelaksanaan Konstruksi (Tanpa Kualifikasi Usaha) yang Disetor Sendiri'],
		['28-409-41', 'Kekurangan penyetoran PPh final dari pemungutan Pihak Lain (SIPP)-Jasa Konstruksi Berupa Jasa Pengawasan Konstruksi (Dengan Kualifikasi Usaha) yang Disetor Sendiri'],
		['28-409-36', 'Kekurangan penyetoran PPh final dari pemungutan Pihak Lain (SIPP)-Jasa Konstruksi Berupa Jasa Perencanaan Konstruksi (Dengan Kualifikasi Usaha) yang Disetor Sendiri'],
		['28-409-39', 'Kekurangan penyetoran PPh final dari pemungutan Pihak Lain (SIPP)-Jasa Konstruksi Berupa Jasa Pelaksanaan Konstruksi (Kualifikasi Usaha Menengah dan Besar) yang Disetor Sendiri'],
		['28-410-01', 'Imbalan yang Diterima/Diperoleh Sehubungan dengan Pengangkutan Orang dan/atau Barang Termasuk Penyewaan Kapal Laut Oleh Perusahaan Pelayaran Dalam Negeri'],
		['28-410-02', 'Imbalan yang Dibayarkan/Terutang kepada Perusahaan Pelayaran Dalam Negeri'],
		['28-410-03', 'Kekurangan penyetoran PPh final dari pemungutan Pihak Lain (SIPP)-Imbalan yang Dibayarkan/Terutang kepada Perusahaan Pelayaran Dalam Negeri'],
		['28-410-04', 'Kekurangan penyetoran PPh final dari pemungutan Pihak Lain (SIPP)-Imbalan yang Diterima/Diperoleh Sehubungan dengan Pengangkutan Orang dan/atau Barang Termasuk Penyewaan Kapal Laut Oleh Perusahaan Pelayaran Dalam Negeri'],
		['28-411-01', 'Imbalan yang Dibayarkan/Terutang kepada Perusahaan Pelayaran dan/atau Penerbangan Luar Negeri Sehubungan dengan Pengangkutan Orang dan/atau Barang (Selain Berdasarkan Perjanjian Charter)'],
		['28-411-02', 'Imbalan Charter Kapal Laut dan/atau Pesawat Udara yang Dibayarkan/ Terutang kepada Perusahaan Pelayaran dan/atau Penerbangan Luar Negeri  melalui BUT di Indonesia'],
		['28-411-03', 'Kekurangan penyetoran PPh final dari pemungutan Pihak Lain (SIPP)-Imbalan Charter Kapal Laut dan/atau Pesawat Udara yang Dibayarkan/ Terutang kepada Perusahaan Pelayaran dan/atau Penerbangan Luar Negeri melalui BUT di Indonesia'],
		['28-413-01', 'Penghasilan Wajib Pajak Luar Negeri yang Mempunyai Kantor Perwakilan Dagang di Indonesia'],
		['28-416-01', 'Revaluasi atau penilaian kembali aset tetap'],
		['28-417-02', 'Bunga Simpanan yang Dibayarkan oleh Koperasi kepada Anggota Wajib Pajak Orang Pribadi (bunga di atas Rp240.000,00)'],
		['28-417-01', 'Bunga Simpanan yang Dibayarkan oleh Koperasi kepada Anggota Wajib Pajak Orang Pribadi (bunga sampai dengan Rp240.000,00)'],
		['28-419-01', 'Dividen yang Diterima/Diperoleh Wajib Pajak Orang Pribadi Dalam Negeri'],
		['28-421-01', 'Uplift Hulu Migas'],
		['28-421-02', 'Participating Interest Eksplorasi Hulu Migas'],
		['28-421-03', 'Participating Interest Eksploitasi Hulu Migas'],
		['28-423-01', 'Pemotongan atau pemungutan PPh atas penjualan barang atau penyerahan jasa yang dilakukan oleh Wajib Pajak dengan peredaran bruto tertentu sesuai dengan Peraturan Pemerintah Nomor 23 Tahun 2018 atau Peraturan Pemerintah Nomor 55 Tahun 2022.'],
		['28-423-02', 'Pemotongan atau pemungutan PPh atas transaksi pembelian yang dilakukan oleh Wajib Pajak dengan peredaran bruto tertentu sesuai dengan Peraturan Pemerintah Nomor 55 Tahun 2022.'],
		['28-423-12', 'Pemotongan atau Pemungutan PPh atas transaksi penjualan barang atau penyerahan jasa yang dilakukan oleh Wajib Pajak yang memenuhi persyaratan tertentu untuk dikenai PPh yang bersifat final dengan tarif 0% di IKN (PPh UMKM di IKN).'],
		['28-423-03', 'Pemotongan atau Pemungutan PPh atas transaksi penjualan barang atau penyerahan jasa yang dilakukan oleh Wajib Pajak orang pribadi yang memiliki peredaran bruto tertentu sesuai dengan PP 55 Tahun 2022 dengan peredaran usaha s.d Rp500.000.000,00'],
		['28-423-13', 'Pemotongan atau pemungutan PPh atas transaksi pembelian yang dilakukan oleh Wajib Pajak yang memanfaatkan fasilitas PPh final dengan tarif 0% di IKN (PPh UMKM di IKN).'],
		['28-423-99', 'Penghasilan yang dikenakan pajak bersifat final sesuai Peraturan Pemerintah Nomor 23/55  (Disetor Sendiri)'],
		['28-432-01', 'Perjanjian Pengikatan Jual Beli'],
		['28-499-01', 'Penghasilan Wajib Pajak yang Melakukan Kegiatan Usaha Jasa Maklon (Contract Manufacturing) Internasional di Bidang Produksi Mainan Anak-Anak'],
		['28-499-02', 'Penghasilan yang Diterima atau Diperoleh Sehubungan dengan Kerja Sama dengan Lembaga Pengelola Investasi (LPI)'],
		['28-499-99', 'Penghasilan istri dari satu pemberi kerja'],
		['28-999-99', 'Penghasilan Final Lainnya']
	],
	l2_b_jenis_penghasilan: [
		['303', 'Dividen atau bagian laba'],
		['401', 'Pembebasan utang'],
		['402', 'Hibah'],
		['403', 'Bantuan/Sumbangan'],
		['404', 'Warisan'],
		['405', 'Penerimaan Zakat dan Sumbangan Keagamaan yang sifatnya wajib'],
		['406', 'Bagian Laba Anggota Perseroan Komanditer Tidak Atas Saham, Persekutuan, Perkumpulan, Firma, Kongsi'],
		['407', 'Klaim asuransi kesehatan, kecelakaan, jiwa, dwiguna, beasiswa'],
		['408', 'Beasiswa'],
		['409', 'Hadiah langsung yang diberikan kepada semua pembeli/konsumen akhir tanpa diundi'],
		['423', 'Objek PPh tertentu bagi TKA yang memiliki keahlian tertentu (expatriate regime)'],
		['424', 'Natura dan kenikmatan yang dikecualikan dari objek pajak'],
		['425', 'SHU dari koperasi'],
		['498', 'Penghasilan lain yang tidak termasuk objek pajak']
	],
	l2_c_jenis_penghasilan: [
		'Penghasilan dari Pekerjaan Bebas',
		'Penghasilan dari kegiatan usaha',
		'Pendapatan lain dari kegiatan usaha atau pekerjaan bebas',
		'Gaji, tunjangan, honorarium, bonus, jasa produksi',
		'Upah honorarium yg diterima oleh pegawai tidak tetap',
		'Uang pesangon diterima sekaligus',
		'Manfaat Pensiun, Tunjangan Hari Tua, atau Jaminan Hari Tua dibayarkan sekaligus',
		'Uang pensiun yang diterima secara berkala/bulanan oleh penerima pensiun',
		'Penghasilan lain yang berhubungan dengan pekerjaan',
		'Sewa tanah dan atau bangunan',
		'Sewa harta selain tanah dan atau bangunan',
		'Dividen',
		'Bunga',
		'Obligasi',
		'Royalti',
		'Keuntungan Penjualan Harta',
		'Bunga Deposito',
		'Bunga Tabungan',
		'Surat Berharga/Sekuritas',
		'Penjualan Saham di Bursa',
		'Pengalihan atau Penjualan Tanah Bangunan',
		'Keuntungan Selisih Mata Uang Asing',
		'Penghasilan lain-lain dari Modal atau Aset/Harta',
		'Pembebasan Utang',
		'Hibah',
		'Bantuan/Sumbangan',
		'Warisan',
		'Hadiah/Undian',
		'Penghasilan lain'
	],
	mata_uang: [
		['AED', 'UAE Dirham: UNITED ARAB EMIRATES'],
		['AFN', 'Afghani Afghanistan'],
		['ALL', 'Albania Lek'],
		['ANG', 'Gulden Antillen Belanda'],
		['ARS', 'Peso Argentina'],
		['AUD', 'Dolar Australia'],
		['AWG', 'Gulden Aruba'],
		['AZN', 'Manat Azerbaijan'],
		['BAM', 'Mark Konvertibel Bosnia dan Herzegovina'],
		['BBD', 'Dolar Barbados'],
		['BDT', 'Bangladeshi Taka'],
		['BGN', 'Lev Bulgaria'],
		['BMD', 'Dolar Bermuda'],
		['BND', 'Dolar Brunei Darussalam'],
		['BOB', 'Boliviano Bolivia'],
		['BRL', 'Real Brazil'],
		['BSD', 'Dolar Bahama'],
		['BWP', 'Pula Botswana'],
		['BYN', 'Rubel Belarusia'],
		['BZD', 'Dolar Belize'],
		['CAD', 'Dolar Kanada'],
		['CHF', 'Franc Swiss'],
		['CLP', 'Peso Chili'],
		['CNY', 'Yuan Renminbi: CHINA'],
		['COP', 'Peso Kolombia'],
		['CRC', 'Kolon Kosta Rika'],
		['CUP', 'Peso Kuba'],
		['CZK', 'Koruna Republik Ceko'],
		['DKK', 'Krone Denmark'],
		['DOP', 'Peso Republik Dominika'],
		['EGP', 'Pound Mesir'],
		['EUR', 'Negara Anggota Euro'],
		['FJD', 'Dolar Fiji'],
		['FKP', 'Kepulauan Falkland (Malvinas) Pound'],
		['GBP', 'Pound Inggris'],
		['GGP', 'Pound Guernsey'],
		['GHS', 'Cedi Ghana'],
		['GIP', 'Pound Gibraltar'],
		['GTQ', 'Quetzal Guatemala'],
		['GYD', 'Dolar Guyana'],
		['HKD', 'Dollar Hongkong'],
		['HNL', 'Lempira Honduras'],
		['HRK', 'Kuna Kroasia'],
		['HUF', 'Forint Hongaria'],
		['IDR', 'Rupiah Indonesia'],
		['ILS', 'Shekel Israel'],
		['IMP', 'Pulau Man Pound'],
		['INR', 'Rupee India'],
		['IRR', 'Rial Iran'],
		['ISK', 'Krona Islandia'],
		['JEP', 'Jersey Pound'],
		['JMD', 'Dolar Jamaika'],
		['JPY', 'Yen Jepang'],
		['KGS', 'Som Kirgistan'],
		['KHR', 'Kamboja Riel'],
		['KPW', 'Won Korea Utara'],
		['KRW', 'Won Korea Selatan'],
		['KYD', 'Dolar Kepulauan Cayman'],
		['KZT', 'Tenge Kazakstan'],
		['LAK', 'Kip Laos'],
		['LBP', 'Pound Lebanon'],
		['LKR', 'Rupee Sri Lanka'],
		['LRD', 'Dolar Liberia'],
		['MKD', 'Denar Makedonia'],
		['MNT', 'Tughrik Mongolia'],
		['MUR', 'Rupee Mauritius'],
		['MXN', 'Peso Meksiko'],
		['MYR', 'Ringgit Malaysia'],
		['MZN', 'Metical Mozambik'],
		['NAD', 'Dolar Namibia'],
		['NGN', 'Naira Nigeria'],
		['NIO', 'Cordoba Nikaragua'],
		['NOK', 'Krone Norwegia'],
		['NPR', 'Rupee Nepal'],
		['NZD', 'Dolar Selandia Baru'],
		['OMR', 'Rial Oman'],
		['PAB', 'Balboa Panama'],
		['PEN', 'Sol Peru'],
		['PHP', 'Peso Filipina'],
		['PKR', 'Rupee Pakistan'],
		['PLN', 'Zloty Polandia'],
		['PYG', 'Guarani Paraguay'],
		['QAR', 'Riyal Qatar'],
		['RON', 'Leu Romania'],
		['RSD', 'Dinar Serbia'],
		['RUB', 'Rubel Rusia'],
		['SAR', 'Riyal Arab Saudi'],
		['SBD', 'Dolar Kepulauan Solomon'],
		['SCR', 'Rupee Seychelles'],
		['SEK', 'Krona Swedia'],
		['SGD', 'Dolar Singapura'],
		['SHP', 'Pound Saint Helena'],
		['SOS', 'Shilling Somalia'],
		['SRD', 'Dolar Suriname'],
		['SVC', 'Kolon El Salvador'],
		['SYP', 'Pound Suriah'],
		['THB', 'Baht Thailand'],
		['TRY', 'Lira Turki'],
		['TTD', 'Dolar Trinidad dan Tobago'],
		['TVD', 'Dolar Tuvalu'],
		['TWD', 'Dolar Baru Taiwan'],
		['UAH', 'Ukraina Ukraina'],
		['USD', 'Dolar Amerika Serikat'],
		['UYU', 'Peso Uruguay'],
		['UZS', 'Som Uzbekistan'],
		['VEF', 'Bolivar Venezuela'],
		['VND', 'Dong Vietnam'],
		['XCD', 'Dolar Karibia Timur'],
		['YER', 'Rial Yaman'],
		['ZAR', 'Rand Afrika Selatan'],
		['ZWD', 'Dolar Zimbabwe']
	],
	l3a4_b_jenis_penghasilan: [
		['207', 'Penggantian atau imbalan yang diberikan dalam bentuk natura atau kenikmatan'],
		['302', 'Sewa harta selain tanah dan/atau bangunan'],
		['304', 'Bunga'],
		['306', 'Royalti'],
		['307', 'Keuntungan karena Penjualan atau karena Pengalihan Harta'],
		['314', 'Imbalan Bunga'],
		['319', 'Keuntungan Seilisih Kurs Mata Uang Asing'],
		['399', 'Penghasilan Lain dari Modal atau Aset'],
		['401', 'Pembebasan Utang'],
		['402', 'Hibah'],
		['403', 'Bantuan/Sumbangan'],
		['407', 'Klaim Asuransi'],
		['408', 'Beasiswa'],
		['409', 'Hadiah'],
		['412', 'Penghasilan Dalam Negeri Lainnya']
	],
	l5_b_jenis: [
		['501', 'Zakat (Sesuai PP Nomor 60 Tahun 2010)'],
		['502', 'Sumbangan keagamaan (Sesuai PP Nomor 60 Tahun 2010)'],
		['503', 'Fasilitas pengurang penghasilan Neto (Tax allowance)'],
		['504', 'Fasilitas keringanan pajak lainnya (Tax reliefs)'],
		['505', 'Pengurang penghasilan neto lainnya']
	],
	l5_c_jenis: [
		['601', 'Fasilitas pembebasan atau pengurangan PPh (Tax holiday)'],
		['603', 'Pengurang PPh Lainnya']
	],
	l3c_harta_berwujud: [
		['0410', 'Mesin'],
		['0412', 'Kapal Pesiar'],
		['0405', 'Kendaraan Angkutan'],
		['0403', 'Mobil Penumpang'],
		['0709', 'Rumah Tangga/Furnitur'],
		['0413', 'Peralatan'],
		['0707', 'Peralatan Olahraga Khusus'],
		['0406', 'Kendaraan Khusus'],
		['0407', 'Kereta'],
		['0408', 'Pesawat Terbang'],
		['0411', 'Gerobak/Troli'],
		['0402', 'Motor'],
		['0499', 'Aset Bergerak Lainnya'],
		['0710', 'Peralatan Lainnya'],
		['0708', 'Peralatan Elektronik'],
		['0401', 'Sepeda'],
		['0409', 'Kapal Laut'],
		['0404', 'Bus'],
		['0711', 'Jet Ski'],
		['0799', 'Aset Lainnya']
	],
	l3c_bangunan: [
		['0502', 'Bangunan untuk tempat tinggal'],
		['0505', 'Apartemen'],
		['0503', 'Bangunan untuk usaha (toko, pabrik, kantor, gudang, dan sejenisnya)'],
		['0599', 'Aset tidak Bergerak Lainnya'],
		['0504', 'Bangunan yang disewakan']
	],
	l3c_harta_tidak_berwujud: [
		['0610', 'Hak Eksploitasi Sumber Daya Alam dan Hasil Alam Lainnya'],
		['0609', 'Hak di Lapangan Minyak dan Gas'],
		['0603', 'Merek dagang'],
		['0607', 'Goodwill'],
		['0601', 'Paten'],
		['0699', 'Harta Tidak Berwujud Lainnya'],
		['0602', 'Royalti'],
		['0608', 'Hak Pengusahaan Hutan'],
		['0604', 'Hak Guna Bangunan'],
		['0605', 'Hak Guna Usaha'],
		['0606', 'Hak Pakai']
	],
	l3c_metode_komersial: [
		['ML', 'Metode Lainnya'],
		['JSP', 'Jumlah Satuan Produksi'],
		['SMG', 'Saldo Menurun Ganda'],
		['JJJ', 'Jumlah Jam Jasa'],
		['JAT', 'Jumlah Angka Tahun'],
		['SM', 'Saldo Menurun'],
		['GL', 'Garis Lurus']
	],
	l3c_metode_fiskal: [
		['GL', 'Garis Lurus'],
		['SM', 'Saldo Menurun'],
		['JSP', 'Jumlah Satuan Produksi']
	],
	l3d_metode_pembebanan: [
		['01', 'Beban Langsung'],
		['02', 'Beban Cadangan']
	],
	l3d_jenis_dokumen: [
		['02', 'Perjanjian Tertulis'],
		['01', 'Penyerahan Perkara'],
		['03', 'Publikasi Penerbitan'],
		['04', 'Pengakuan Debitur']
	],
	l3d_jenis_biaya_promosi: [
		['EXHIBITION', 'Biaya pameran produk'],
		['INTRODUCTION', 'Biaya pengenalan produk baru'],
		['BENEFIT', 'Penggantian atau imbalan yang diberikan dalam bentuk natura atau kenikmatan'],
		['ADVERTISING', 'Biaya periklanan di media elektronik, media cetak, dan/atau media lainnya'],
		['SPONSORSHIP', 'Biaya sponsorship yang berkaitan dengan promosi produk']
	],
};

export const run = async ({ db }: SeedContext) => {
	const rows = Object.entries(daftar).flatMap(([nama, items]) =>
		items.map((item, index) => ({
			daftar: nama,
			urutan: index + 1,
			nama: typeof item === 'string' ? item : item[1],
			kode: typeof item === 'string' ? null : item[0]
		}))
	);

	await batchInsert(
		db,
		rows.map((row) =>
			db
				.insert(referensi_lampiran_spt_pph_orang_pribadi)
				.values({ id: `ref-op-${row.daftar}-${row.urutan}`, ...row })
				.onConflictDoUpdate({
					target: [
						referensi_lampiran_spt_pph_orang_pribadi.daftar,
						referensi_lampiran_spt_pph_orang_pribadi.urutan
					],
					set: { nama: row.nama, kode: row.kode, aktif: true }
				})
		)
	);

	await db
		.update(referensi_lampiran_spt_pph_orang_pribadi)
		.set({ aktif: false })
		.where(notInArray(referensi_lampiran_spt_pph_orang_pribadi.daftar, Object.keys(daftar)));

	console.log(
		`Seeded SPT PPh Orang Pribadi lampiran references: ${rows.length} options across ${Object.keys(daftar).length} lists (${rows.filter((r) => r.kode !== null).length} with a kode)`
	);

	return [];
};
