export const enum AuthUserStatus {
	ACTIVE = 'ACTIVE',
	SUSPENDED = 'SUSPENDED',
	DELETED = 'DELETED',
}

export const enum AuthProvider {
	GOOGLE = 'GOOGLE',
	GITHUB = 'GITHUB',
	MICROSOFT = 'MICROSOFT',
}

export const enum AuthTokenPurpose {
	EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
	PASSWORD_RESET = 'PASSWORD_RESET',
	MAGIC_LINK = 'MAGIC_LINK',
}

export const enum MfaFactorType {
	TOTP = 'TOTP',
}

export const enum AuthSecurityEventType {
	USER_REGISTERED = 'USER_REGISTERED',
	EMAIL_VERIFIED = 'EMAIL_VERIFIED',
	LOGIN_SUCCESS = 'LOGIN_SUCCESS',
	LOGIN_FAILED = 'LOGIN_FAILED',
	LOGOUT = 'LOGOUT',
	PASSWORD_CHANGED = 'PASSWORD_CHANGED',
	PASSWORD_RESET_REQUESTED = 'PASSWORD_RESET_REQUESTED',
	PASSWORD_RESET_COMPLETED = 'PASSWORD_RESET_COMPLETED',
	SESSION_REVOKED = 'SESSION_REVOKED',
	REFRESH_TOKEN_REUSED = 'REFRESH_TOKEN_REUSED',
	MFA_ENABLED = 'MFA_ENABLED',
	MFA_DISABLED = 'MFA_DISABLED',
	USER_SUSPENDED = 'USER_SUSPENDED',
}