<script lang="ts">
	import { page as appPage } from '$app/state';
	import { formatMonth } from '$lib/helpers/date';
	import { formatRupiah } from '$lib/helpers/rupiahInput';
	import { ptkpEbupotOptions } from '$lib/helpers/ptkp-ebupot';
	import { untrack } from 'svelte';
	import { getFasilitasPajakBp21 } from '../../fasilitasPajak.remote';
	import { getJenisDokumenEbupot } from '../../jenisDokumen.remote';
	import { getObjekPajakBp21 } from '../../objekPajakBp21.remote';
	import { getWajibPajak } from '../../../getWajibPajak.remote';
	import { getBp21 } from './getBp21.remote';
	import { submitBp21 } from './submitBp21.remote';
	import { terbitkanBp21 } from '../terbitkanBp21.remote';
	import { updateBp21 } from './updateBp21.remote';
	import { ActionButton, Breadcrumbs, DocumentWorkspace, FieldGrid, FormActions, FormField, FormSection, InlineAlert, LookupField, PageLayout, RupiahField, SelectField, ServiceWorkspace, Stack } from '$lib/re-ui-components';

	const bp21 = await getBp21();
	const [objekPajakOptions, fasilitasOptions, jenisDokumenOptions] = await Promise.all([getObjekPajakBp21(), getFasilitasPajakBp21(), getJenisDokumenEbupot()]);
	let masaPajakState = $state(bp21.masaPajak); let tahunState = $state(bp21.tahun); let nomorIdentitasWpState = $state(bp21.nomorIdentitasWp); let namaPenerimaState = $state(bp21.namaPenerima); let statusPtkpState = $state(bp21.statusPtkp ?? ''); let kodeObjekPajakIdState = $state(bp21.kodeObjekPajakId ?? ''); let fasilitasPajakIdState = $state(bp21.fasilitasPajakId ?? '');
	const selectedObjekPajak = $derived(objekPajakOptions.find((o) => o.id === kodeObjekPajakIdState)); const selectedFasilitas = $derived(fasilitasOptions.find((f) => f.id === fasilitasPajakIdState)); const nitkuPenerima = $derived(nomorIdentitasWpState ? `${nomorIdentitasWpState}000000` : ''); const nitkuPemotong = `${bp21.npwpPemotong}000000`;
	const cumulativeObjectCodes = ['21-401-01', '21-401-02']; const isCumulativeObject = $derived(selectedObjekPajak ? cumulativeObjectCodes.includes(selectedObjekPajak.kode) : false);
	let penghasilanBrutoState = $state(bp21.penghasilanBruto); let pendapatanBrutoSebelumnyaState = $state(bp21.pendapatanBrutoSebelumnya);
	const bandContains = (band: { Min: number; Max: number }, amount: number) => amount >= band.Min && amount <= band.Max;
	const taxAtCumulativeBracket = (bands: { Min: number; Max: number; Rate: number; Minus?: number }[], amount: number) => { if (amount <= 0) return { tax: 0, rate: 0 }; const band = bands.find((b) => bandContains(b, amount)); if (!band) return { tax: 0, rate: 0 }; return { tax: amount * (band.Rate / 100) - (band.Minus ?? 0), rate: band.Rate }; };
	const resolvedBp21 = $derived.by(() => { if (!selectedObjekPajak || !selectedFasilitas) return null; const item = selectedObjekPajak.parameterData.ItemList.find((entry) => entry.TaxCertificateCode === selectedFasilitas.kode || entry.TaxCertificateCodes?.includes(selectedFasilitas.kode)); if (!item) return null; const manualDpp = item.ManualDeemedRate?.toUpperCase() === 'TRUE'; const manualTarif = item.ManualTaxRate?.toUpperCase() === 'TRUE'; const manualIncomeTax = item.ManualIncomeTaxWithheld?.toUpperCase() === 'TRUE'; const dppPercent = item.DeemedRate ?? 0; const taxBase = penghasilanBrutoState * (dppPercent / 100); const bands = item.Rates ?? []; const maxBruto = bands.length > 0 && dppPercent > 0 ? Math.max(...bands.map((band) => band.Max)) / (dppPercent / 100) : undefined; if (isCumulativeObject && bands.some((band) => band.Minus !== undefined)) { const total = pendapatanBrutoSebelumnyaState + penghasilanBrutoState; const { tax: taxOnTotal, rate } = taxAtCumulativeBracket(bands, total); const { tax: taxOnPrevious } = taxAtCumulativeBracket(bands, pendapatanBrutoSebelumnyaState); return { dppPercent, tarif: rate, manualDpp, manualTarif, manualIncomeTax, pajakPenghasilanOverride: Math.round((taxOnTotal - taxOnPrevious) * (dppPercent / 100)), maxBruto }; } const terBands = bands.filter((band) => band.TaxExemptionStatus !== undefined); if (terBands.length > 0) { const applicable = terBands.filter((band) => band.TaxExemptionStatus?.includes(statusPtkpState)); const band = applicable.find((candidate) => bandContains(candidate, taxBase)); return { dppPercent, tarif: band?.Rate ?? 0, manualDpp, manualTarif, manualIncomeTax, pajakPenghasilanOverride: undefined, maxBruto }; } if (bands.length > 0) { const band = bands.find((candidate) => bandContains(candidate, taxBase)); return { dppPercent, tarif: band?.Rate ?? 0, manualDpp, manualTarif, manualIncomeTax, pajakPenghasilanOverride: band?.Minus !== undefined ? Math.round(taxBase * (band.Rate / 100) - band.Minus) : undefined, maxBruto }; } if (typeof item.Rate === 'number') return { dppPercent, tarif: item.Rate, manualDpp, manualTarif, manualIncomeTax, pajakPenghasilanOverride: undefined, maxBruto: undefined }; return { dppPercent, tarif: 0, manualDpp, manualTarif, manualIncomeTax, pajakPenghasilanOverride: undefined, maxBruto: undefined }; });
	let dppManualState = $state(bp21.dpp); let tarifManualState = $state(bp21.tarif); $effect(() => { if (resolvedBp21) { dppManualState = resolvedBp21.dppPercent; tarifManualState = resolvedBp21.tarif; } });
	const pajakPenghasilanDefault = $derived(resolvedBp21?.pajakPenghasilanOverride ?? Math.round((penghasilanBrutoState * dppManualState * tarifManualState) / 10000)); let pajakPenghasilanManualState = $state(bp21.pajakPenghasilan); $effect(() => { if (resolvedBp21) pajakPenghasilanManualState = untrack(() => pajakPenghasilanDefault); });
	async function cariNpwpPenerima() { const wp = await getWajibPajak({ npwp: nomorIdentitasWpState }); if (wp) namaPenerimaState = wp.nama; else if (nomorIdentitasWpState && confirm(`TIN ${nomorIdentitasWpState} saat ini belum terdaftar dalam sistem. Sistem akan otomatis menggunakan TIN 9990000000999000 sebagai TIN penerima penghasilan.`)) { namaPenerimaState = `PENERIMA PENGHASILAN#${nomorIdentitasWpState}`; nomorIdentitasWpState = '9990000000999000'; } }
	const months = Array.from({ length: 12 }, (_, i) => i + 1); const accountName = $derived(String(appPage.data.user?.name ?? 'Wajib Pajak')); const accountNpwp = $derived(String(appPage.data.user?.username ?? '')); let sidebarOpen = $state(false);
</script>

<svelte:head><title>e-Bupot BP21</title></svelte:head>
{#snippet formContent()}
	<div class="form-stack">
		<FormSection number="01" title="Informasi Umum" bordered>
			<FieldGrid>
				<SelectField label="Masa Pajak" name="masaPajak" value={masaPajakState} disabled={!bp21.canEdit} options={months.map((m) => ({ value: m, label: formatMonth(m) }))} onchange={(v) => (masaPajakState = Number(v))} />
				<FormField label="Tahun" name="tahun" type="number" bind:value={() => String(tahunState), (v) => (tahunState = Number(v))} disabled={!bp21.canEdit} />
				<FormField label="Status" value={bp21.status} disabled />
				<FormField label="NITKU/Nomor Identitas Subunit Organisasi Penerima Penghasilan" value={nitkuPenerima} disabled />
				<LookupField label="Nomor Identitas WP (Penerima)" name="nomorIdentitasWp" bind:value={nomorIdentitasWpState} buttonLabel="Cari NPWP" buttonVisible={bp21.canEdit} disabled={!bp21.canEdit} inputmode="numeric" maxlength={16} onlookup={cariNpwpPenerima} />
				<FormField label="Nama Penerima" name="namaPenerima" bind:value={namaPenerimaState} disabled={!bp21.canEdit} />
			</FieldGrid>
		</FormSection>
	<FormSection number="02" title="Dokumen Referensi" bordered><FieldGrid><SelectField label="Jenis Dokumen" name="jenisDokumenId" value={bp21.jenisDokumenId ?? ''} disabled={!bp21.canEdit} options={jenisDokumenOptions.map((d) => ({ value: d.id, label: d.nama }))} /><FormField label="Nomor Dokumen" name="nomorDokumen" value={bp21.nomorDokumen} disabled={!bp21.canEdit} /><FormField label="Tanggal Dokumen" name="tanggalDokumen" type="date" value={bp21.tanggalDokumen ?? ''} disabled={!bp21.canEdit} /><FormField label="NITKU/Nomor Identitas Sub Unit Organisasi" value={nitkuPemotong} disabled /></FieldGrid></FormSection>
	<FormSection number="03" title="Pajak Penghasilan (Rp)" bordered><FieldGrid><SelectField label="Status PTKP" name="statusPtkp" value={statusPtkpState} disabled={!bp21.canEdit} options={ptkpEbupotOptions.map((p) => ({ value: p.value, label: p.label }))} onchange={(v) => (statusPtkpState = String(v))} /><SelectField label="Fasilitas Pajak yang Dimiliki oleh Penerima Penghasilan" name="fasilitasPajakId" value={fasilitasPajakIdState} disabled={!bp21.canEdit} options={fasilitasOptions.map((f) => ({ value: f.id, label: f.nama }))} onchange={(v) => (fasilitasPajakIdState = String(v))} /><SelectField label="Nama Objek Pajak" name="kodeObjekPajakId" value={kodeObjekPajakIdState} disabled={!bp21.canEdit} options={objekPajakOptions.map((o) => ({ value: o.id, label: o.nama }))} onchange={(v) => (kodeObjekPajakIdState = String(v))} /><FormField label="Jenis Pajak" value={selectedObjekPajak?.pasal ?? ''} disabled /><FormField label="Kode Objek Pajak" value={selectedObjekPajak?.kode ?? ''} disabled /><FormField label="Sifat Pajak Penghasilan" value={selectedObjekPajak?.sifat ?? ''} disabled />
	{#if isCumulativeObject}<RupiahField label="Pendapatan Bruto yang Telah Dibayar Sebelumnya (Khusus untuk Kode Objek Pajak 21-401-01 dan 21-401-02)" name="pendapatanBrutoSebelumnya" bind:value={pendapatanBrutoSebelumnyaState} disabled={!bp21.canEdit} />{/if}<RupiahField label="Penghasilan Bruto (Rp)" name="penghasilanBruto" bind:value={penghasilanBrutoState} disabled={!bp21.canEdit} />
	{#if resolvedBp21?.maxBruto !== undefined && penghasilanBrutoState > resolvedBp21.maxBruto}<div class="wide"><InlineAlert tone="error" title="Peringatan">Penghasilan Bruto melebihi nilai maksimum untuk objek pajak ini (Rp{formatRupiah(resolvedBp21.maxBruto)}).</InlineAlert></div>{/if}
	{#if resolvedBp21?.manualDpp}<FormField label="DPP (%)" name="dppManual" type="number" bind:value={() => String(dppManualState), (v) => (dppManualState = Number(v))} disabled={!bp21.canEdit} />{:else}<FormField label="DPP (%)" value={String(resolvedBp21?.dppPercent ?? bp21.dpp)} disabled />{/if}{#if resolvedBp21?.manualTarif}<FormField label="Tarif (%)" name="tarifManual" type="number" bind:value={() => String(tarifManualState), (v) => (tarifManualState = Number(v))} disabled={!bp21.canEdit} />{:else}<FormField label="Tarif (%)" value={String(resolvedBp21?.tarif ?? bp21.tarif)} disabled />{/if}{#if resolvedBp21?.manualIncomeTax}<RupiahField label="Pajak Penghasilan (Rp)" name="pajakPenghasilanManual" bind:value={pajakPenghasilanManualState} disabled={!bp21.canEdit} />{:else}<RupiahField label="Pajak Penghasilan (Rp)" value={pajakPenghasilanDefault} disabled />{/if}<FormField label="KAP-KJS" value={selectedObjekPajak?.kap ?? ''} disabled /><p class="hint wide">{#if resolvedBp21?.manualDpp || resolvedBp21?.manualTarif || resolvedBp21?.manualIncomeTax}DPP, Tarif, dan/atau Pajak Penghasilan untuk kombinasi ini dapat diisi manual.{:else}DPP, Tarif, dan Pajak Penghasilan dihitung otomatis dari kombinasi Status PTKP, Nama Objek Pajak, Fasilitas Pajak, dan Penghasilan Bruto saat disimpan.{/if}</p></FieldGrid></FormSection>
	{#if bp21.canEdit}<FormActions><ActionButton type="button" tone="quiet" onclick={() => (window.location.href = '/ebupot/bp21')}>Kembali</ActionButton><ActionButton type="submit">Simpan Konsep</ActionButton></FormActions>{:else}<FormActions><ActionButton type="button" tone="quiet" onclick={() => (window.location.href = '/ebupot/bp21')}>Kembali</ActionButton></FormActions>{/if}
</div>
{/snippet}
<PageLayout contentWidth="1540px"><Stack gap="16px"><Breadcrumbs separator="›" items={[{ label: 'Beranda', href: '/dashboard' }, { label: 'e-Bupot', href: '/ebupot/bp21' }, { label: 'BP21' }]} /><ServiceWorkspace bind:sidebarOpen identity={{ eyebrow: 'Wajib Pajak', name: accountName, identifier: accountNpwp, mark: 'EB' }} groups={[{ label: 'e-Bupot', links: [{ label: 'Bukti Potong Saya', href: '/ebupot/bukti-potong-saya' }, { label: 'BPPU', href: '/ebupot/bpu' }, { label: 'BP21', href: '/ebupot/bp21', active: true }, { label: 'BP26', href: '/ebupot/bp26' }, { label: 'BPA1', href: '/ebupot/bpa1' }, { label: 'BPA2', href: '/ebupot/bpa2' }, { label: 'Bukti Pemotongan Bulanan Pegawai Tetap', href: '/ebupot/mp' }]}]}><DocumentWorkspace>
{#if bp21.canEdit}<form {...updateBp21}>{@render formContent()}</form><FormActions>{#if bp21.status !== 'SUBMITTED'}<form {...submitBp21}><ActionButton type="submit" tone="danger">Submit</ActionButton></form>{:else}<form {...terbitkanBp21.for(bp21.id)}><ActionButton type="submit" tone="secondary">Terbitkan</ActionButton></form>{/if}</FormActions>{:else}{#if bp21.nomorPemotongan}<p>Nomor Pemotongan: <code>{bp21.nomorPemotongan}</code></p>{/if}{@render formContent()}{/if}
</DocumentWorkspace></ServiceWorkspace></Stack></PageLayout>

<style>
.form-stack { display: grid; gap: 18px; }
.wide { grid-column: 1 / -1; display: flex; gap: 10px; align-items: end; }
.wide :global(.field) { flex: 1; }
.hint { color: var(--ui-muted); font-size: 13px; }
</style>
